### ISSUE TITLE
Maven Repo Down

### ISSUE THREAD

**Issue by hoemblem** [Azure/mmlspark#1005]
**Describe the bug**
The maven repo is currently unavailable: https://mmlspark.azureedge.net/maven & cannot be found on our cluster when we try to run our code.

**To Reproduce**
1. Call library on Databricks cluster
2.Library not found for Maven coords

**Expected behavior**
1. Clusters should be able to use repo

**Info (please complete the following information):**
 - MMLSpark Version: mmlspark_2.11:1.0.0-rc3
 - Spark Version 6.4 (includes Apache Spark 2.4.5, Scala 2.11)
 - Spark Platform: Databricks

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by hoemblem** [comment]
This was resolved on our side.

**Comment by mengban** [comment]
> This was resolved on our side.

how to fix? I can't vist the website [https://mmlspark.azureedge.net/maven](https://mmlspark.azureedge.net/maven) on my PC either.

**Comment by imatiach-msft** [comment]
@mengban the website can't be visited via brower (there is no "website").  It's just the maven resolver for artifacts.  You need to specify the resolver in order to be able to get the mmlspark jars.  It's working fine right now, there is no outage.

**Comment by mengban** [comment]
> @mengban the website can't be visited via browser (there is no "website"). It's just the maven resolver for artifacts. You need to specify the resolver in order to be able to get the mmlspark jars. It's working fine right now, there is no outage.

Thanks a lot. I have added the url as a resolver for artifacts and it works fine. But another question is that how to know the jars list in the maven repo? 
In my case, when add library by
`libraryDependencies += "com.microsoft.ml.spark" %% "mmlspark" % "1.0.0-rc3"`
it didn't work.
And I got the right way by reading issues:
`libraryDependencies += "com.microsoft.ml.spark" %% "mmlspark" % "1.0.0-rc3-85-c987ad0b-SNAPSHOT"
`
so, I want to know the jars list in the maven repo url, do you have any good idea?
