### ISSUE TITLE
Maven Repository updated for Spark 3, Scala 2.12 compatibility

### ISSUE THREAD

**Issue by rgordon** [Azure/mmlspark#1031]
I'd like to use mmlspark in a Databricks cluster, but the currently-available Maven coordinate is only compatible with Scala 2.11 - and I'd like to use Spark 3, Scala 2.12 at least.

Not sure what the protocol is, who manages the release build, etc.

**Comment by rgordon** [comment]
This is related to recent work on https://github.com/Azure/mmlspark/issues/813 - you may or may not consider it a duplicate - to me it's possibly a separate part of the release.

**Comment by imatiach-msft** [comment]
hi @rgordon please see my reply here:
https://github.com/Azure/mmlspark/issues/295#issuecomment-827100538
you can use any of the recent builds, including the latest master build, for example:

com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-59-bf337941-SNAPSHOT
Repository
https://mmlspark.azureedge.net/maven

we support spark3 and scala 2.12 on master

**Comment by rgordon** [comment]
Okay, I'll give that a try - thanks.

**Comment by rgordon** [comment]
Yes, that works, thanks. Is there any sort of "official" release scheduled?

**Comment by malthe** [comment]
@imatiach-msft where are the newer docker images that support Spark 3 located?
