### ISSUE TITLE
Finding the mapping of string class labels to integer indices used by a TrainedClassifierModel

### ISSUE THREAD

**Issue by mawah** [Azure/mmlspark#105]
Hi folks,

I created a TrainedClassifierModel using a training dataset in which the label column is string-valued. I've noticed that when I apply the TrainedClassifierModel's `transform` method to a validation dataset, the resulting `scored_labels` column is integer-valued: presumably those are integer indices for the predicted labels. To produce a human-interpretable result, I'd like to map the `scored_labels` values back to their corresponding strings.

- How can I find the label-to-index mapping that the TrainedClassifierModel has learned? Is it exposed as an attribute?
- Suppose that I manually mapped my string-valued labels to consecutive integer indices beginning at zero, then used that integer column as my label column during training. Will MMLSpark adopt my integer-valued labels as its own class indices, or is there a potential for permutation?
   - If the former is true, then I would know exactly how to map `scored_labels` indices back to strings.
   - The latter may be true e.g. if MMLSpark simply assigns indices to labels in the order it encounters them.

Thanks!

**Comment by imatiach-msft** [comment]
we can add a transform to map back the scored labels, but as a workaround for now you can use the index to value transform.
Thank you, Ilya

**Comment by mawah** [comment]
Thanks again @imatiach-msft! The IndexToString feature transformer in pyspark.ml.feature did the trick for me so I'll close this issue. (Not sure whether you were thinking of adding this as an option for trained models' transform() method; if so, might want to add it to the backlog if that hasn't been done already.)
