### ISSUE TITLE
Add support for missing value cleaner

### ISSUE THREAD

**Issue by rastala** [Azure/mmlspark#11]
Add an Estimator that computes a missing value replacement value, such as mean, median or mode, for training data. The Estimator then produces a Model that can be applied to replace missing values.

The missing value cleaner should support one or more input columns. Different types should be supported as follows:

- Floating point numbers: mean, median, mode
- Integer numbers: median, mode
- Strings and categoricals: model
- Vectors and other composite types: not supported

The missing value cleaner should be a PipelineStage so it is compatible with SparkML pipelines.

**Comment by drdarshan** [comment]
Closing since the basic missing value cleaner transform is now merged in #22
