### ISSUE TITLE
Only one spark slave node worked while training

### ISSUE THREAD

**Issue by JWenBin** [Azure/mmlspark#1147]
spark version: 2.4.7
scala version: 2.11.12
lightgbmlib version: 2.2.350
mmlspark_2.11 version: 0.18.1
Spark slaves: 2 slaves

submit command：
spark-submit --master yarn --driver-cores 2 --driver-memory 3G --num-executors 2 --executor-memory 18G --executor-cores 14 --conf spark.dynamicAllocation.enabled=false --conf spark.default.parallelism=140 --jars s3://EMR/jars/jasypt-1.9.2.jar,s3://EMR/jars/spark-mllib_2.11-2.4.0.jar,s3://EMR/jars/commons-pool2-2.0.jar,s3://EMR/jars/mmlspark_2.11-0.18.1.jar,s3://EMR/jars/lightgbmlib-2.2.350.jar --class myclassName myLgbm.jar

trainning code:
```
    val classifier = new LightGBMClassifier() 
      .setLabelCol("play")
      .setObjective("binary")
      .setCategoricalSlotNames(categoryArray)
      .setUseBarrierExecutionMode(true) 
      .setFeaturesCol("gbdtFeature")
      .setPredictionCol("predictPlay")
      .setNumIterations(trees) 
      .setNumLeaves(32)
      .setLearningRate(0.01)
      .setProbabilityCol("probabilitys")
      .setEarlyStoppingRound(200).setBoostingType("gbdt").setLambdaL2(0.002).setMaxDepth(24)
  println("trainDF partitions: ",trainDF.rdd.getNumPartitions) // 70
  val lgbmModel0 =classifier.fit(trainDF.limit(90000000))
```

problem:
Only one task running while train at "reduce at LightGBMBase.scala:88" or "reduce at LightGBMBase.scala:90", and only one spark  slave running.  

spark history server screenshot:
![图片](https://user-images.githubusercontent.com/49393828/127472290-ba90646b-d5bf-4e3e-a5e4-52c6dfeb363b.png)
![图片](https://user-images.githubusercontent.com/49393828/127475391-2036b09a-2abe-4c23-ab40-371f540ed954.png)
![图片](https://user-images.githubusercontent.com/49393828/127487115-a90a885c-6b2f-4410-8afb-72064d53d42c.png)

"top info" about my two spark slave:
![图片](https://user-images.githubusercontent.com/49393828/127487287-43b7c4f8-937f-4788-be8a-93e26fb2c4ad.png)
![图片](https://user-images.githubusercontent.com/49393828/127487304-40a12bf4-0426-437d-826a-1ffb3d1dd907.png)

**I haven't seem this problem before, and I remember that I can train parallel with all spark slaves last year. But I almost forgot it. How to use all spark slaves to train the model for faster performance?
Thank in advance!**

**Comment by imatiach-msft** [comment]
@JWenBin that is very strange!  That should just work and use two tasks.  One thing I noticed, you are using a very old version of mmlspark, 0.18.1, can you upgrade to the rc-3 release or do you have to use maven central?
I don't see anything obvious from your parameters.  I do see:

```
--num-executors 2
```

One thing that could be a problem is that there is only a single partition in your spark dataframe, but I also see:
```
  println("trainDF partitions: ",lgbmTrainDF.rdd.getNumPartitions) // 70
```
If there are 70 partitions that shouldn't be a problem.

What do you see if you set this to false instead of true and don't use barrier execution mode:
      .setUseBarrierExecutionMode(false) 

Do you still see the same behavior and does the spark history server screenshot change?

**Comment by JWenBin** [comment]
> rc-3
After upgrade to the rc-3 release 
.setParallelism("voting_parallel")

**Comment by JWenBin** [comment]
It looks like if I use "trainDF.limit(90000000)" limit befor trainning, my trainning data set will be reparation to a single partition. And cpu utilization will be about 100%, **although there only one slave running, it still faster than cluster parallel trainning model.** **Because  CPU utilization is too low when trainning data set was reparation to more than one partition** .

**Comment by JWenBin** [comment]
> 
> 
> @JWenBin that is very strange! That should just work and use two tasks. One thing I noticed, you are using a very old version of mmlspark, 0.18.1, can you upgrade to the rc-3 release or do you have to use maven central?
> I don't see anything obvious from your parameters. I do see:
> 
> ```
> --num-executors 2
> ```
> 
> One thing that could be a problem is that there is only a single partition in your spark dataframe, but I also see:
> 
> ```
>   println("trainDF partitions: ",lgbmTrainDF.rdd.getNumPartitions) // 70
> ```
> 
> If there are 70 partitions that shouldn't be a problem.
> 
> What do you see if you set this to false instead of true and don't use barrier execution mode:
> .setUseBarrierExecutionMode(false)
> 
> Do you still see the same behavior and does the spark history server screenshot change?

Thank for your help.  
Now I get my currently  maximize CPU utilization by ".repartition(sparkSlaveNums)" repartition my data set equal to spark slave machines. Still not sure ".setNumTasks(sparkSlaveNums)" would be helpful for improve CPU utilization.
![图片](https://user-images.githubusercontent.com/49393828/127860146-a7b38130-85eb-4abc-96e6-6977c40166b5.png)
![图片](https://user-images.githubusercontent.com/49393828/127860092-4dfe35c9-16ac-460c-a545-e2f3a5a02eda.png)

THX!
