### ISSUE TITLE
Sentiment Analysis documentScores is unavailable

### ISSUE THREAD

**Issue by Stargatto** [Azure/mmlspark#1153]
Hi to all,

According to the official Microsoft Sentiment Analysis API documentation, both 3.0 and 3.1 version of the API return a field called _confidenceScores_ that contains the predicted scores associated with the labels (positive, negative and neutral) related to the analyzed document. 

From documentation:

> Sentiment Analysis in version 3.x applies sentiment labels to text, which are returned at a sentence and document level, with a confidence score for each.

When we call the API through the pyspark mmlspark.cognitive.TextSentiment module (we use the mmlspark 1.0.0-rc3 version on a Azure Synapse Spark Pool v2.4), it seems that the _confidenceScore_ is named in the output dataframe as _documentScores_. 
However, this field results always undefined as shown below: 

```
sentiment = (TextSentiment()\ 
    .setTextCol(text_column)\ 
    .setOutputCol("output")\ 
    .setSubscriptionKey(service_key)\ 
    .setLocation(sentiment_location)\ 
    .setLanguage(sentiment_language)\ 
) 

display(sentiment.transform(df).select("Analized_Text", col("output")[0].getItem("documentScores"))) 
```
 
Output: 

![immagine](https://user-images.githubusercontent.com/5358399/128080523-3938036b-6cbf-4fba-9da6-cd7375bcbe93.png)

**Comment by mhamilton723** [comment]
@Stargatto this is fixed in master and could possibly be in the spark3 version on synapse. Would you mind switching over to the spark 3 pool to see?

**Comment by Stargatto** [comment]
@mhamilton723 yes, using an Apache Spark v3 pool in Azure Synapse, confidence scores are now present with the correct names. Thank you!
