### ISSUE TITLE
Performance difference while using mmlspark package mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT as compared to mmlspark_2.11:1.0.0-rc3

### ISSUE THREAD

**Issue by bipin2295** [Azure/mmlspark#1161]
We are using mmlspark package to train lightgbm model in spark 3 and spark 2. In spark 3 we are using package mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT which takes around 40 minutes to complete, which in spark 2 we are using mmlspark_2.11:1.0.0-rc3 which completes in around 20-25 minutes. Can you help me understand what could be the possible problem here?

**Comment by mhamilton723** [comment]
Thanks for raising this @bipin2295! @imatiach-msft has made many improvements since rc3 and its possible something regressed. Mind sharing a minimal repro?

**Comment by imatiach-msft** [comment]
@bipin2295 can you try the latest package with useSingleDatasetMode=True?  Do you see any performance difference there?
