### ISSUE TITLE
MMLSpark model.save changes dfs working directory

### ISSUE THREAD

**Issue by akshaya-a** [Azure/mmlspark#133]
With the following diagnostic code,

    hdi_wd = get_hdispark_working_dir()
    print("AFTER STATS TRANSFORM, BEFORE WRITE")
    print(hdi_wd)
    
    # save model
    model.save("outputs/aot-mmlspark.model")
    hdi_wd = get_hdispark_working_dir()
    print("AFTER WRITE")

AFTER STATS TRANSFORM, BEFORE WRITE
wasb://**snip**/testhdi_1505503317753
Running HDI/Spark job in wasb://**snip**
AFTER WRITE

Regular spark model:
Running HDI/Spark job in wasb://**snip**/testhdi_1505505091869
BEFORE WRITE
wasb://**snip**/testhdi_1505505091869
Running HDI/Spark job in wasb://**snip**/testhdi_1505505091869
AFTER WRITE
wasb://**snip**/testhdi_1505505091869

**Comment by mhamilton723** [comment]
hhmmm, thats odd because looking at the save code there doesn't seem to be any directory changing smoking guns. Is this a blocking issue?
