### ISSUE TITLE
Support cross-validation based FindBestModel

### ISSUE THREAD

**Issue by rastala** [Azure/mmlspark#14]
Add a new Estimator - FindBestModelCV - that is like FindBestModel, but uses cross-validation instead of evaluation against dataset. 

FindBestModelCV would take a list of **un-trained** model or models, do cross-validation for each of them using the same fold splits, and compare metrics. It would then train the best model against full data, and return that as output Model.

Additionally, FindBestModelCV should produce a table of metrics for all sweeps.

**Comment by mhamilton723** [comment]
We should delete FindBestModel as it duplicates funtionality from sparks CrossValidation and GridSearch models. If we decide to keep FindBestModel it should use these spark primitives, and the MetaEstimator (see the new stages PR) under the hood.

**Comment by rastala** [comment]
AFAIK, SparkML CV and GridSearch have the limitation that you can't sweep over different types of models that expect different data layout, for example logistic regression vs random forest with categorical data. However, with FindBestModel you can do this, because it supports implicit featurization strategies.

**Comment by imatiach-msft** [comment]
This issue is resolved by the randomized grid search hyperparameter tuner (with cross validation)
