### ISSUE TITLE
LightGBMClassifier on OSX

### ISSUE THREAD

**Issue by julioasotodv** [Azure/mmlspark#290]
I believe that the mmlspark jar pushed for spark packages (version 0.12) has C libraries inside, and perhaps are just .so files for Linux.

Therefore, when using LightGBMClassifier on spark on OS X, the following error is raised:
```
18/04/19 12:21:34 WARN TaskSetManager: Lost task 2.0 in stage 4.0 (TID 41, localhost, 
executor driver): 
java.lang.UnsatisfiedLinkError: Could not load the native libraries 
because we encountered the following problems: no _lightgbm in java.library.path and 
Could not find resource /com/microsoft/ml/lightgbm/osx/x86_64/lib_lightgbm.dylib in jar
```
Given that IMO the best idea is that every user builds is own LightGBM with the SWIG wrapper (just to avoid creating multiple jars for every mmlspark version and OS), wouldn't it be a better idea to put LightGBM on Apache Spark on a separate repo and add it to mmlspark as such?

That way LightGBM on Apache Spark could be built with less dependencies on any OS, while still being part of mmlspark for those that need the whole project

Either that or I am doing something wrong somewhere :)

**Comment by imatiach-msft** [comment]
@julioasotodv sorry, we only test running spark on linux right now (windows and OS X are currently not tested).  I added the SWIG Java wrappers to LightGBM, the logic to construct the jar file, and built and uploaded the jar to maven central.  Prior to uploading to maven I should probably build lightGBM on OS X and add the related osx/x86_64/lib_lightgbm.dylib files to the jar.

**Comment by imatiach-msft** [comment]
@julioasotodv Sorry, could you please elaborate more on:
"Perhaps it is better idea to add com.microsoft.ml.lightgbm as a "by hand" requirement before installation, and remove it from mmlspark dependencies?"
Sorry, I'm not sure what you mean by a by-hand requirement?  It needs to be a dependency because the lightGBM classifier and regressor depend on the package.

**Comment by imatiach-msft** [comment]
closing as mac OS support has been added to latest master
