### ISSUE TITLE
Load LightGBM native model

### ISSUE THREAD

**Issue by ericwang915** [Azure/mmlspark#293]
Hello, team, I have a lightgbm model trained using python lightgbm pkg and would like to load the model and use it in spark for streaming purpose.

Do your guys know how to load the existing “txt” or “lgb” model using scala in mmlspark? I tried to read all the documents but cannot find a clue.

By the way, please also provide a scala example for us to learn about how to using lightgbm in scala？ Similar to the pyspark example.

Example might include:

(1) How to train the model in a classification and regression scenario？
(2) How to load a existing  model?
(3) How to use to model for model serving？
(4) How to validate the model's metrics？

**Comment by imatiach-msft** [comment]
closing with latest fix merged to master
