### ISSUE TITLE
pyspark RandomForestClassifier featureImportances

### ISSUE THREAD

**Issue by dvanasseldonk** [Azure/mmlspark#301]
Hi team,

Is it possible to retrieve featureImportances from pyspark RandomForestClassifier when using TrainClassifier from mmlspark.

Something like this?

model = TrainClassifier(model=RandomForestClassifier(numTrees=20, maxDepth=20), labelCol="Click", 
            numFeatures=100
                ).fit(train)

print(model.featureImportances)

**Comment by imatiach-msft** [comment]
@dvanasseldonk This looks like a good feature to add - there needs to be an easy way to retrieve the underlying model easily in the pyspark API.
if this was in scala you could do:
model.model.stages.last.featureImportances()

**Comment by mhamilton723** [comment]
Thanks for raising this issue, we are hoping to make this API a bit more tightly integrated with sparkML soon!

**Comment by dvanasseldonk** [comment]
Thanks guys!

**Comment by imatiach-msft** [comment]
@dvanasseldonk closing this issue as it has been fixed with https://github.com/Azure/mmlspark/pull/414 and should be in the next release (0.15) - but anyone can get it by using the latest build from master
