### ISSUE TITLE
Retrieving model hyperparameters

### ISSUE THREAD

**Issue by dvanasseldonk** [Azure/mmlspark#302]
Hi team,

Can you advise how to retrieve model hyperparameters from logistic regression after using FindBestModel?

My current code is:

logisticRegressions = [LogisticRegression(regParam = hyperParam)
                        for hyperParam in lrhyperParams]
lrmodels = [TrainClassifier(model=lrm, labelCol="Click", numFeatures=256).fit(train)
                        for lrm in logisticRegressions]
print("----training done-----")

# Select the best model
bestModel = FindBestModel(evaluationMetric = "AUC", models = lrmodels).fit(test)

print("---getBestModelInfo----")
print(bestModel._java_obj.getBestModelInfo)
print("---getRegParam----")
print(bestModel._java_obj.getRegParam)
---------------------------------------------------

which prints this:
----training done-----
---getBestModelInfo----
<py4j.java_gateway.JavaMember object at 1y6f87c4bce127>
---getRegParam----
<py4j.java_gateway.JavaMember object at 1y3f87c4de15f9>

**Comment by imatiach-msft** [comment]
@dvanasseldonk thank you for the feedback!  You are correct, those methods are available only on the scala side and not generated automatically on the python side.
We should eventually expose the methods on the models written in scala in the python generator automatically, but for now you can use this:

from py4j.java_gateway import java_import
from pyspark.ml.common import _java2py
java_import(sc._gateway.jvm, "org.apache.spark.sql.*")
metrics = _java2py(sc, bestModel._java_obj.getAllModelMetrics())

I don't see methods getBestModelInfo or getRegParam, see here for all methods on the best model:
https://github.com/Azure/mmlspark/blob/master/src/find-best-model/src/main/scala/FindBestModel.scala#L181

Hope this helps!

**Comment by dvanasseldonk** [comment]
Thanks @imatiach-msft, I'm trying:

print("---getBestModelInfo----")
allmodelmetrics = _java2py(sc, bestModel._java_obj.getAllModelMetrics())
bestmodelmetrics = _java2py(sc, bestModel._java_obj.getBestModelMetrics())
print(allmodelmetrics)
print(bestmodelmetrics)

and receive this output:

---getBestModelInfo----
DataFrame[model_name: string, metric: double, parameters: string]
DataFrame[evaluation_type: string, predicted_class_as_0.0_actual_is_0.0: double, predicted_class_as_0.0_actual_is_1.0: double, predicted_class_as_1.0_actual_is_0.0: double, predicted_class_as_1.0_actual_is_1.0: double, accuracy: double, precision: double, recall: double, AUC: double]

Is there an additional step to find the underlying data?

**Comment by imatiach-msft** [comment]
@dvanasseldonk 
you can just do:
allmodelmetrics.show()
or:
allmodelmetrics.toPandas()

**Comment by dvanasseldonk** [comment]
Thanks @imatiach-msft!
