### ISSUE TITLE
Power 8 Availability 

### ISSUE THREAD

**Issue by jtfogarty** [Azure/mmlspark#303]
We are looking to compile mmlspark on our IBM Power 8 server.  Has this been attempted?  We seen postings that mmlspark is for Intel only and not for ppc64le

Thanks

**Comment by mhamilton723** [comment]
Hey @jtfogarty, thanks for trying out MMLSpark. Most of our library should be fairly portable, though these pieces might be the tricky parts:

- CNTK on Spark uses CNTK's JAR which only has natives for linux and windows. 
- Some parts of the build rely on bash (though we are trying to move away from this and any PRs in this area would be greatly appreciated!)
- LightGBM on Spark uses their JAR which is very similar to CNTK's
- OpenCV on spark uses an OpenCV java jar that comes with its own natives

Hope this helps!

**Comment by jtfogarty** [comment]
Hi Mark, 
Thanks for the response.

We got pass CNTK configuration and dependencies but when we attempt compilation we encountered the below;
 
 fatal error: x86intrin.h: No such file or directory

Any ideas how to resolve this?

Thanks again.

**Comment by mhamilton723** [comment]
Hhhm, I dont have any experience with Power8 myself, but the the CNTK team would be of more help here as this seems to be the blocker. @thiagocrepaldi (who isnt in this repo so I cant link to him) is the current maintainer of the CNTK library and might know more about the feasibility of this and how to unblock you. I would suggest opening up an issue over there 
https://github.com/Microsoft/CNTK/issues
and tagging him directly to ask. Please let us know what he says about this! Good luck and I will try to help wherever possible!

**Comment by thiagocrepaldi** [comment]
I am not familiar with development on Power8 as well. Each platform has its own development libs/headers.
Did you try https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa ?
