### ISSUE TITLE
LightGBM feature Importances

### ISSUE THREAD

**Issue by bigdataexplorer** [Azure/mmlspark#310]
In Spark, we can get the feature importances from GBT and Random Forest. Can we do the same with LightGBM ?

**Comment by ywskycn** [comment]
Also looking for same information. Not sure whether LightGBMClassificationModel provides an API for accessing such information.

**Comment by imatiach-msft** [comment]
@bigdataexplorer @ywskycn yes, this is definitely possible to do, we just need to add the functionality

**Comment by bigdataexplorer** [comment]
Anything I can help ?

**Comment by mhamilton723** [comment]
@imatiach-msft does light GBM provide this API? If not this might be a bigger add

**Comment by imatiach-msft** [comment]
@mhamilton723 yes it does, it should be simple to add

**Comment by ywskycn** [comment]
I think we can just add a new API in LightGBMBooster, calling LGBM_BoosterFeatureImportance() in c_api.cpp.

**Comment by imatiach-msft** [comment]
@bigdataexplorer @rohanmonga @ywskycn @mhamilton723 I added a PR here for feature importances in LightGBM: https://github.com/Azure/mmlspark/pull/333

**Comment by imatiach-msft** [comment]
@bigdataexplorer @rohanmonga @ywskycn @mhamilton723 the PR has been checked in so closing this issue - it will be in the next release (0.14) or you can use the latest custom build:

--packages com.microsoft.ml.spark:mmlspark_2.11:0.13.dev0+1.ga8e702f 
--repositories https://mmlspark.azureedge.net/maven

**Comment by rohanmonga** [comment]
thank you!

**Comment by bigdataexplorer** [comment]
Thanks alot @imatiach-msft ! I will give it a try.

**Comment by lind1022** [comment]
Hey guys, for pyspark LightGBM (mmlspark.lightgbm), `getFeatureImportances` only returns a list of values, but they don't map to the feature names, is there a workaround of that?

**Comment by mmchougule** [comment]
@imatiach-msft for PySpark `getFeatureImportances`, is there a workaround for returning a dict of feature names and values vs. just returning a list of values?
