### ISSUE TITLE
Executors run at different training paces in LightGBMClassifier

### ISSUE THREAD

**Issue by ywskycn** [Azure/mmlspark#318]
Just launched a simple LightGBMClassifier job, with 5 executors and each executor has 1 core. I found that different executors run at different paces, as seen in [log](https://gist.github.com/ywskycn/299decb6ca59ef1eba41d409e3f12ca8). Executor2 finishes quite early, while Executor1 is still running. Talk to @guolinke offline, and the executors should be at the same pace. 

Some configs I used (I changed some code to inject more params): num_iterations=100, bagging_fraction=0.8, bagging_freq=5, feature_fraction=0.8, num_leaves=63, min_sum_hessian_in_leaf=5.0, metric_freq=1, is_training_metric=true, min_data_in_leaf=50.

Not sure whether anyone has ideas? @imatiach-msft @mhamilton723  FYI

**Comment by imatiach-msft** [comment]
@ywskycn according to the output log:
https://gist.github.com/ywskycn/299decb6ca59ef1eba41d409e3f12ca8
one of the executors ran to 65 iterations while the other ran to the full 100 iterations, which is unexpected.
The "running iteration" log is coming from here:
https://github.com/Azure/mmlspark/blob/02642ce4fd1fc447d5e25e30e6a64d0b845da4f1/src/lightgbm/src/main/scala/TrainUtils.scala#L80
This is very unexpected for me, as trainParams.numIterations should be the same across all executors (100).

**Comment by imatiach-msft** [comment]
@ywskycn @guolinke I wonder if we need to synchronize the executors so that we have to block on each iteration?  I assumed this was already taken care of inside lightgbm.  eg should each iteration be a mappartitions (or if that is too costly maybe I need to add some synchronization logic for the executors/driver inside a single mapparitions)?

**Comment by ywskycn** [comment]
@imatiach-msft sorry for the confusion. The Executor 1 is still running (and current is round 65). I copied the log earlier before it finished. All executors finally finished at 100 iterations, but with different time.

**Comment by ywskycn** [comment]
BTW, @imatiach-msft  is it possible to double-check whether your local env has same issue? Just to make sure we're in the same page

**Comment by ywskycn** [comment]
ok. After more debugging, the problem is, each executor still runs at serial mode, although passing "data_parallel". Will add a PR to fix this issue. BTW, I think this should also explain my previous accuracy questions...

**Comment by imatiach-msft** [comment]
@ywskycn it's great to hear that you have found the bug.  Sorry, could you give more info on how the executors are running in serial mode?

**Comment by ywskycn** [comment]
@imatiach-msft, the issue that LightGBM still needs "numMachines" parameter. Created https://github.com/Azure/mmlspark/pull/323
