### ISSUE TITLE
Including column names when saving LightGBM native model?

### ISSUE THREAD

**Issue by ywskycn** [Azure/mmlspark#332]
When using LightGBMBooster.saveNativeModel() function, it looks like the model doesn't include original column names, but using "Column_*" instead. Do I miss any config here? @little-eyes @imatiach-msft

**Comment by ywskycn** [comment]
I think this is because I use spark pipeline model, where assembles all feature columns into one vector, and the lightgbm library doesn't have the original feature column names.. Not sure any good solution to add column names back, or need to implement sth like https://github.com/jpmml/jpmml-sparkml-xgboost?

**Comment by imatiach-msft** [comment]
@ywskycn yes, this is definitely something that needs to be fixed and @little-eyes already saw this issue before.  I need to figure out a way to pass the column names to vector assembler and then from vector assembler pass them to native lightgbm code.  It's something that would need to be investigated.

**Comment by imatiach-msft** [comment]
closing as PR to include column names (when they are available on slot metadata in features column) has been merged, see PR #526 
The fix should be available in next release.
