### ISSUE TITLE
LightGBM Param timeout does not exist

### ISSUE THREAD

**Issue by little-eyes** [Azure/mmlspark#334]
Hi,

I'm running the new version 0.13, but it seems like we are getting the following error:

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-3708616085001278> in <module>()
      8   numIterations=100)
      9 
---> 10 model = model.fit(train)
     11 
     12 #scoredData = model.transform(test)

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/databricks/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    286 
    287     def _fit(self, dataset):
--> 288         java_model = self._fit_java(dataset)
    289         model = self._create_model(java_model)

```scala
from mmlspark import LightGBMClassifier
model = LightGBMClassifier(
  maxBin=64,
  numLeaves=128,
  learningRate=0.1,
  parallelism="voting_parallel",
  labelCol="LabelIndex",
  numIterations=100)

model = model.fit(train)
```

**Comment by imatiach-msft** [comment]
hi @little-eyes , sorry about the error you are seeing, could you send me the full error log - I only see the stack trace in the java side and I don't see the full error message.  Also, how is the error related to the title ("LightGBM Param timeout does not exist"), I don't see anything mentioning timeout in the description above.
