### ISSUE TITLE
Spark 2.3 on Azure ML Workbench to enable Apache Arrow

### ISSUE THREAD

**Issue by dvanasseldonk** [Azure/mmlspark#338]
Is there a way to run Spark 2.3 on the Azure ML Workbench with the currently available mmlspark baseDockerImages?

I'm looking to enable Apache Arrow to improve the speed of .toPandas() on spark dataframes which requires Spark 2.3.

**Comment by mhamilton723** [comment]
Hey @dvanasseldonk thanks for reaching out! We have already updated to spark 2.3, but i do not know if the workbench has updated yet. I would direct this question to the AML team here:

https://feedback.azure.com/forums/34192--general-feedback

which is the feedback tool at the bottom of this page:
https://docs.microsoft.com/en-us/azure/machine-learning/service/quickstart-installation
