### ISSUE TITLE
Support LightGBM for multiple class classification

### ISSUE THREAD

**Issue by ericwang915** [Azure/mmlspark#342]
Currently, LGB in mmlspark only supports binary classification. When will you consider supporting the multiple class classification?

**Comment by ericwang915** [comment]
I saw you marked it as TODO in

https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

I hope this part will be updated soon.

**Comment by ekerazha** [comment]
Is this planned for version 0.14? This is an important feature that "plain" LightGBM supports, but we can't use it in mmlspark

**Comment by imatiach-msft** [comment]
closing this issue as fix has been merged as part of https://github.com/Azure/mmlspark/pull/461
FYI @ekerazha @ericwang915
