### ISSUE TITLE
Tweedie for LightGBM

### ISSUE THREAD

**Issue by nightflight-dk** [Azure/mmlspark#353]
Hello please add support for Tweedie and regressor export (only classifier can be saved today), thanks

**Comment by imatiach-msft** [comment]
@nightflight-dk tweedie is already available as one of the options:

https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/main/scala/LightGBMRegressor.scala#L47

Regressor export has already been added here:

https://github.com/Azure/mmlspark/pull/333/files

but only after the official v0.13 release, you can use a custom build instead however, eg:

--packages com.microsoft.ml.spark:mmlspark_2.11:0.13.dev18+3.gab13363
--repositories https://mmlspark.azureedge.net/maven


Hope this helps!

**Comment by nightflight-dk** [comment]
Thank you for a quick response Ilya, for full Tweedie support please add the option to configure the variance power vs keeping the default 1.5. Early stopping rounds and verbosity during the training would be welcome as well. We could followup internally if you prefer, my alias dakowalc

**Comment by imatiach-msft** [comment]
@nightflight-dk thanks, I've sent a PR to add the variance power parameter to LightGBM regressor.
I will look into adding early stopping and verbosity as well.

**Comment by imatiach-msft** [comment]
@nightflight-dk  The PR built successfully (and the test I added also passed), you can use the custom build with the following params:

--packages com.microsoft.ml.spark:mmlspark_2.11:0.13.dev21+1.gca24275
--repositories https://mmlspark.azureedge.net/maven.

Let me know if you get a chance to test it out, thanks!

**Comment by nightflight-dk** [comment]
Impressive resolve time Ilya, thank you. I can confirm the setters now in use on my cluster.

Unfortunately  I am running into allocation errors and timing-out / lost workers, java.net.ConnectException: Connection refused (Connection refused)

Even on a large cluster with small dataset (96 cores, <1M data points with 20 features) but I suppose it’s not related to your changes.

Any ETA for GPU support in the Spark version? Distributed multi-GPU training on partitioned RDD’s would be a fantastic addition.

Thanks, Damian

Cloud + AI
Market Intelligence
dakowalc@microsoft.com<mailto:dakowalc@microsoft.com>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by imatiach-msft** [comment]
@nightflight-dk closing this issue as tweedie variance power parameter has been merged in

**Comment by nightflight-dk** [comment]
Thank you!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
