### ISSUE TITLE
Need to specify to native lightgbm learner if given columns are categorical

### ISSUE THREAD

**Issue by imatiach-msft** [Azure/mmlspark#367]
Need to specify to native lightgbm learner if given columns are categorical
Creating issue to track this based on conversation with @gopinutakki [here](https://github.com/Azure/mmlspark/issues/317#issuecomment-416713183)

**Comment by imatiach-msft** [comment]
When we assemble column in spark we should propagate any columns that were indexed (via stringindexer or our valueindexer) to lightgbm native code

**Comment by imatiach-msft** [comment]
updating based on conversation [here](https://github.com/Azure/mmlspark/issues/317#issuecomment-416724076) -- it looks like it should be an easy fix, see here:
https://github.com/Microsoft/LightGBM/blob/93764fda72ed3f7144455abd1e616f98be71c554/docs/Parameters.rst#categorical_feature
and here:
https://github.com/Microsoft/LightGBM/blob/93764fda72ed3f7144455abd1e616f98be71c554/docs/Advanced-Topics.rst#categorical-feature-support
We just need to supply this parameter with the known categorical columns to lightgbm. We can expose this parameter to the user in case the user knows they are categorical and also we can automatically infer the columns that are categorical if they have been string indexed/value indexed based on the DataFrame metadata

**Comment by friyal** [comment]
So the https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/main/scala/LightGBMUtils.scala do not encode the categorical features and I should transform the dataset before by myself?

**Comment by imatiach-msft** [comment]
@friyal  if you use the helper method featurizeData it will actually one-hot-encode the categoricals, but that is just a helper method.  LightGBMClassifier/Regressor uses the Spark ML api so it can be compatible with all spark transforms (eg CrossValidator), which only takes in a vector of doubles for the features column.

**Comment by ekerazha** [comment]
Could you please expose this parameter so we can use the native LightGBM categorical features support? This is really important if we have categorical features with MANY levels and one-hot encoding is not feasible

**Comment by imatiach-msft** [comment]
fix has been merged to master

**Comment by imatiach-msft** [comment]
reopening as it looks like fix wasn't correct, the name/index passed to lightgbm should be for the slot and not for a column name, good thing this isn't released yet

**Comment by imatiach-msft** [comment]
fixed again with new PR #463
