### ISSUE TITLE
Support initial score for LightGBM training

### ISSUE THREAD

**Issue by superbobry** [Azure/mmlspark#382]
LightGBM [allows](https://lightgbm.readthedocs.io/en/latest/Parameters.html#continued-training-with-input-score) providing an initial score for boosting on top of an existing predictor. However, this functionality is not yet exposed in the Spark wrapper. The user API could be as simple as 

```scala
new LightGBMClassifier()
    .setInitScoreCol("init")
```

However, I am not sure what would be the best way to pass this information to the C++ level. A temporary file, perhaps?

**Comment by imatiach-msft** [comment]
Hi @superbobry , sorry about the trouble you are having.  It looks like there is a parameter that can be passed to LightGBM to specify the init score filename:
https://github.com/Microsoft/LightGBM/blob/6214657aed2c9c682e1937748d39d5bf78698164/docs/Parameters.rst#initscore_filename
But I don't think this is very scalable for a large dataset, and preferable we should be able to pass this data in-memory.  It looks like there is a way to set the InitScore on a dataset directly:
https://github.com/Microsoft/LightGBM/blob/6488f319f243f7ff679a8e388a33e758c5802303/include/LightGBM/dataset.h#L95
However, this is not exposed in the c_api.h file which we currently wrap for LightGBM:
https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h
I like your idea of using a specific column in the dataset for the init score.  I think I may need to add a method to the c_api.h file to allow setting the init_score on the dataset in LightGBM.  Adding @guolinke for context.

**Comment by imatiach-msft** [comment]
while looking through source code at another issue, I stumbled upon this:
https://github.com/Microsoft/LightGBM/blob/0a4a7a86f5a1d3146c36c7d8c082154a193d4893/src/io/dataset.cpp#L534
which can be set here:
https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L948
so actually this should be straightforward to add

**Comment by imatiach-msft** [comment]
closing as #560 has been merged to master and should be in next release.  You can also use the build from master here:

--packages 
com.microsoft.ml.spark:mmlspark_2.11:0.17.dev4+2.gab61448
 and --repositories 
https://mmlspark.azureedge.net/maven
