### ISSUE TITLE
Support latest Spark 2.4

### ISSUE THREAD

**Issue by parasharshah** [Azure/mmlspark#385]
When models trained with Spark 2.4 are deployed on Spark 2.3 ACI/AKS – Operationalization doesn’t work. 
Databricks has released new runtime 5.0 which has Spark 2.4. 
O16n PySpark image has a dependency on MMLSpark so we would like to request an upgrade of MMLSpark image to Spark 2.4.

**Comment by imatiach-msft** [comment]
@parasharshah , @mhamilton723 just updated to spark 2.4, so closing this issue
