### ISSUE TITLE
-

### ISSUE THREAD

**Issue by antoniocachuan** [Azure/mmlspark#386]
-

**Comment by imatiach-msft** [comment]
Hi,
You should only need the option
"--packages Azure:mmlspark:0.14"
The other options shouldn't matter.  MMLSpark should work anywhere where spark is deployed, it shouldn't matter what cluster you are using.  Having said that, I've only tested it on Azure Databricks and HDInsight.  If you want to meet over skype I could try and debug it with you, but I don't have access to a cloudera workbench unfortunately :(.
Thank you, Ilya

**Comment by imatiach-msft** [comment]
@antoniocachuan 
Can you also try on spark 2.3?  We only support spark 2.3 now (older versions support 2.2).
You can also send me an email at mmlspark-support@microsoft.com if you want to diagnose your issue.

**Comment by antoniocachuan** [comment]
@imatiach-msft  
Thanks for your answer, In this moment is not possible to test it in Spark 2.3. Also I tried with `"--packages Azure:mmlspark:0.14"` in Google Cloud Data Proc cluster with the same results.

PD: I really appreciate your help, just emailed you. 

Regards,
Antonio C.

**Comment by imatiach-msft** [comment]
@antoniocachuan the strange thing is, I don't see any errors anywhere.  It looks like you retrieved the jar so you would think that it would just work.  I'm not quite sure what the problem might be.  We could try and add the python files manually from the zip to see if anything fails.  Otherwise, when using --packages it should just pick up the python files and import them.  My guess is something in the import step if failing, but that might not be the case because I don't see an error anywhere.

**Comment by antoniocachuan** [comment]
@imatiach-msft  I tried in CDH running --package using the Scala API and It works, now I am getting a error related to the issue #335  also I could test adding manually the python files.

` spark2-shell --master yarn --packages Azure:mmlspark:0.14,com.microsoft.ml.lightgbm:lightgbmlib:2.1.250
`

![image](https://user-images.githubusercontent.com/4010332/46545832-0d119480-c88d-11e8-8ba6-e8aeb29beedf.png)

Error #335 

`Caused by: java.lang.UnsatisfiedLinkError: /data/06/yarn/nm/usercache/s16746/appcache/application_1538195866523_1970/container_e100_1538195866523_1970_01_000002/tmp/mml-natives2115945537512894448/lib_lightgbm.so: /lib64/libm.so.6: version GLIBC_2.23 not found (required by /data/06/yarn/nm/usercache/s16746/appcache/application_1538195866523_1970/container_e100_1538195866523_1970_01_000002/tmp/mml-natives2115945537512894448/lib_lightgbm.so)
`

**Comment by vinglogn** [comment]
@antoniocachuan  I also encountered the similar problem of ‘No module named mmlspark’，but I compile the source code of mmlspark-0.15, i install 'mmlspark-0.15-py2.py3-none-any.whl' package to my ubuntu16.04 envrionment，this problem is gone！

**Comment by kunguang** [comment]
@antoniocachuan hello, have you solved this question? can you give me some advise ,thanks
![image](https://user-images.githubusercontent.com/3446934/50673318-dd069880-1017-11e9-86ce-edd997e517c5.png)
