### ISSUE TITLE
How to make the mmlspark.jar

### ISSUE THREAD

**Issue by flybywind** [Azure/mmlspark#395]
after `runme`, I cant find the mmlspark.jar in root target directory. In each seperate subdirectory, there is an individual jar for its own target.

**Comment by imatiach-msft** [comment]
@flybywind it should be under the BuildArtifacts folder after the ./runme script is run.  The runme script creates the BuildArtifacts folder and puts all output there.

**Comment by flybywind** [comment]
I have test failures, so the artifact not generated. I'll open a new issue for that.
