### ISSUE TITLE
mmlspark build error

### ISSUE THREAD

**Issue by land1725** [Azure/mmlspark#398]
Hello,When I download the mmlspark source and rebuild it ,it can not build successfully.
my Env is Centos 7.3.
This is the log 
error] /root/mmlspark/src/lightgbm/src/main/scala/BlockManagerUtils.scala: Header does not match expected text
[error] /root/mmlspark/src/lightgbm/src/main/scala/BlockManagerUtils.scala:3:0: Whitespace at end of line
[info] scalastyle Processed 11 file(s)
[info] scalastyle Found 2 errors
[info] scalastyle Found 26 warnings
[info] scalastyle Found 0 infos
[info] scalastyle Finished in 2 ms
[success] created output: /root/mmlspark/src/lightgbm/target
[error] Total time: 2 s, completed 2018-10-16 11:40:30
!!! Error: failure when running sbt full-build
[runmeError.log](https://github.com/Azure/mmlspark/files/2481343/runmeError.log)

**Comment by imatiach-msft** [comment]
@land1725 it looks like you have scala style errors.  That is strange.  Did you make any changes to the file:
mmlspark/src/lightgbm/src/main/scala/BlockManagerUtils.scala
It looks like on line 3 you have extra whitespace at the end of the line.
If you like, we could meet over skype to debug together, maybe that would be faster?
Hope this helps!

**Comment by mhamilton723** [comment]
Hey, because Ilya has found the root of this issue I will close it. Please feel free to reach out to our support alias, mmlspark-support@microsoft.com for more assistance!
