### ISSUE TITLE
add weight to lightgmb

### ISSUE THREAD

**Issue by stevekuo4** [Azure/mmlspark#411]
in our use case we need to include sample weight for model training, which is no available for LightGBMClassifier

**Comment by imatiach-msft** [comment]
this has been resolved with PR #426 , the fix will be in the next release of mmlspark v0.15.  You can test out the fix with the build here:

--packages
com.microsoft.ml.spark:mmlspark_2.11:0.14.dev30+2.gb5960fb
and --repositories
https://mmlspark.azureedge.net/maven
