### ISSUE TITLE
build from source (runme) failure

### ISSUE THREAD

**Issue by puyvqi** [Azure/mmlspark#412]
![image](https://user-images.githubusercontent.com/11178311/47555055-72f9b500-d93d-11e8-8876-2e9963006304.png)
===========================
!!! Error: failure when running curl -f --location --retry 20 --retry-max-time 60 --connect-timeout 120 --speed-limit 10 --speed-time 120 --progress-bar --output /tmp/jdk.tgz https://cdn.azul.com/zulu/bin/zulu8.28.0.1-jdk8.0.163-linux_x64.tar.gz

curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
!!! Error: failure when running curl -f --location --retry 20 --retry-max-time 60 --connect-timeout 120 --speed-limit 10 --speed-time 120 --progress-bar --output /tmp/jdk.tgz https://cdn.azul.com/zulu/bin/zulu8.28.0.1-jdk8.0.163-linux_x64.tar.gz

======================
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
===============================
build failed
can not get the https://cdn.azul.com/zulu/bin/zulu8.28.0.1-jdk8.0.163-linux_x64.tar.gz 
did anyone else meet this before?
did i lack some config?
i cannot even access this site https://cdn.azul.com

**Comment by puyvqi** [comment]
it still dont work for me,i changed my DNS and tried again.
it can download the file this time,but so slow and always disconnected on half.
it seem that it is my network problem.
and i am in ShangHai, this website might be blocked from me?

**Comment by drdarshan** [comment]
Thanks for letting us know. If Azul CDN is not accessible for you, perhaps you could point to an alternate location for a JDK? You need to change the URL in: https://github.com/Azure/mmlspark/blob/master/tools/config.sh#L66 and potentially the checksum on the next line and rerun `runme`. 

Please let us know if this helps.

**Comment by puyvqi** [comment]
thank you very much!
it helps!
I just change https to http ,it works.

**Comment by puyvqi** [comment]
but i stuck in another place，after  installing the needed packages. build process stop for a long time (3 hours)in this place:
![image](https://user-images.githubusercontent.com/11178311/47982448-b1942a00-e10a-11e8-9d4c-dc9a3a011e51.png)

**Comment by imatiach-msft** [comment]
@puyvqi I've seen those tests fail locally as well, you can ignore them.  You can ignore tests by using:

./runme TESTS=NONE

The tests=none can be in front of runme as well:

TESTS=NONE ./runme

**Comment by mhamilton723** [comment]
I cannot repro the issue. Please mention me if you are encountering this and I will re-open the issue
