### ISSUE TITLE
Can I change MMLSpark temp file dir?

### ISSUE THREAD

**Issue by tanjiaxin** [Azure/mmlspark#427]
Hello, I have encoutered a problem that mmlspark will write some tmp files at /tmp when running a application but the tmp file became to large , so I want to change the mmlspark tmp file dir  to a large. How can I change the mmlspark tmp file dir?  and those tmp files are similar to "mmlnatives998512162530320580" .  Thanks in advance.

**Comment by imatiach-msft** [comment]
@tanjiaxin sorry about the trouble you are having.  Hmm, I'm honestly not sure why those files are being generated, maybe @mhamilton723 might know?  Also, could you share the script you are running which is generating those files?

**Comment by tanjiaxin** [comment]
@imatiach-msft according to my observation， the files start with "mmlsparkxxxxx" will genenrated when some job failed.
And here is the notebook file I run the application,
[increment_train_CV.zip](https://github.com/Azure/mmlspark/files/2560078/increment_train_CV.zip)

**Comment by mhamilton723** [comment]
yes these temp files build up because like many temporary files are deleted when the JVM closes normally. When the JVM crashes unexpectedly, the requisite cleanup code is not run. Feel free to delete these files.

**Comment by tanjiaxin** [comment]
@mhamilton723 Thanks for your explaination.

**Comment by mhamilton723** [comment]
Thanks @tanjiaxin let me know if I should re-open this!
