### ISSUE TITLE
Custom metrics for fitting

### ISSUE THREAD

**Issue by Fungie** [Azure/mmlspark#433]
Is it possible to use custom metric when using LightGBM in mmlspark?

Using regular LightGBM in python I would normally use a metric such as:

```
def lgb_average_precision_score(y_hat, data):
    y_true = data.get_label()
    return 'avg_precision_score', average_precision_score(y_true, y_hat), True
```

I don't see any mention of it in the documentation.

On a different note: Is there a weighting feature also with mmlspark version LightGBM?

**Comment by imatiach-msft** [comment]
instance weights were just added recently, but they are not in the latest released version.  You would have to use a private build:
https://github.com/Azure/mmlspark/pull/426

--packages
com.microsoft.ml.spark:mmlspark_2.11:0.14.dev30+2.gb5960fb
and --repositories
https://mmlspark.azureedge.net/maven

**Comment by imatiach-msft** [comment]
@Fungie  sorry, forgot to mention, currently there are no custom metrics but we should be able to support it eventually, so this would be a new feature that we could add in the future to lightgbm on mmlspark

**Comment by imatiach-msft** [comment]
closing issue as this has been implemented in PR:
https://github.com/Azure/mmlspark/pull/1054
relevant issues:
https://github.com/Azure/mmlspark/issues/873, https://github.com/Azure/mmlspark/issues/871, https://github.com/Azure/mmlspark/issues/433
