### ISSUE TITLE
How to deploy the mmlspark app on the spark clusters?

### ISSUE THREAD

**Issue by xiaoxiaofengzi** [Azure/mmlspark#437]
I want to use LightGBM module of mmlspark on the spark cluster, where there are three Datanodes and one Namenode. Should I make mmlspark on Namenode only or Namenode and three Datanodes? Thank you very much!

**Comment by mhamilton723** [comment]
Hey @xiaoxiaofengzi, you should use our spark package to automatically install the code on all the needed machines. You can find out more at this section of our readme:

https://github.com/Azure/mmlspark#setup-and-installation

Please let me know if you run into trouble

**Comment by xiaoxiaofengzi** [comment]
@mhamilton723 Thank you very much! I have got it!
