### ISSUE TITLE
No FileSystem for scheme: dbfs

### ISSUE THREAD

**Issue by vinglogn** [Azure/mmlspark#455]
I compile the source code of mmlspark-0.15, i install  'mmlspark-0.15-py2.py3-none-any.whl' package  to my ubuntu16.04 envrionment, and copy the 'mmlspark_2.11-0.15.jar' and 'mmlspark_2.11-0.15.jar' to the $SPARK_HOME/jars directory.

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export JRE_HOME=$JAVA_HOME/lib
export CLASS_PATH=$CLASS_PATH:$JAVA_HOME/lib:$JRE_HOME/lib
export SPARK_HOME=/opt/spark
export SPARK_CLASSPATH=$SPARK_HOME/jars
export HADOOP_HOME=/usr/local/hadoop
export PYSPARK_PYTHON=/usr/bin/python3
export PYTHONPATH=${SPARK_HOME}/python/:$(echo ${SPARK_HOME}/python/lib/py4j-*-src.zip):${PYTHONPATH}
export PYSPARK_DRIVER_PYTHON="jupyter"
export PYSPARK_DRIVER_PYTHON_OPTS="notebook"
export PATH=$HADOOP_HOME/bin:$SPARK_HOME/bin:$JAVA_HOME/bin:$PATH

when i run the jupyter example of 
 '304 - Medical Entity Extraction with a BiLSTM'

modelName = "BiLSTM"
modelDir = "models"
if not os.path.exists(modelDir): os.makedirs(modelDir)
d = ModelDownloader(spark, "dbfs:///" + modelDir)
modelSchema = d.downloadByName(modelName)
nltk.download("punkt", "/dbfs/nltkdata")
nltk.data.path.append("/dbfs/nltkdata")

It arise the following error,  I don't know why it happen? 
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-06f4b4b8caa7> in <module>
      2 modelDir = "models"
      3 if not os.path.exists(modelDir): os.makedirs(modelDir)
----> 4 d = ModelDownloader(spark, "dbfs:///" + modelDir)
      5 modelSchema = d.downloadByName(modelName)
      6 nltk.download("punkt", "/dbfs/nltkdata")

/usr/local/lib/python3.5/dist-packages/mmlspark/ModelDownloader.py in __init__(self, sparkSession, localPath, serverURL)
     80         self._ctx = sparkSession.sparkContext
     81         self._model_downloader = self._ctx._jvm.com.microsoft.ml.spark.ModelDownloader(
---> 82             sparkSession._jsparkSession, localPath, serverURL)
     83 
     84     def _wrap(self, iter):

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1523         answer = self._gateway_client.send_command(command)
   1524         return_value = get_return_value(
-> 1525             answer, self._gateway_client, None, self._fqn)
   1526 
   1527         for temp_arg in temp_args:

/opt/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.ModelDownloader.
: java.io.IOException: No FileSystem for scheme: dbfs
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at com.microsoft.ml.spark.HDFSRepo.<init>(ModelDownloader.scala:60)
	at com.microsoft.ml.spark.ModelDownloader.<init>(ModelDownloader.scala:219)
	at com.microsoft.ml.spark.ModelDownloader.<init>(ModelDownloader.scala:216)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by imatiach-msft** [comment]
@vinglogn we have two sets of notebooks, one for HDI cluster compute and the other for local compute - they are generated from one set of notebooks during build time.  I think you are running the HDI cluster notebook locally which is causing the problem.  It looks like you don't have dbfs available in the environment you are running the notebook from.

**Comment by vinglogn** [comment]
@imatiach-msft   Is there a 'dbfs' jar package for me to deal with this losing dependency package at my local computer envrionment ? and what is 'dbfs', do you have some wiki?

**Comment by vinglogn** [comment]
@imatiach-msft I am very appreciated for your reply! you tell me there are two two sets of notebooks, HDI cluster compute and local compute environment, and my problem is with the latter。Actually， I pull a docker image of mmlspark from official docker hub, and all the notebooks run well，I want to know the difference between the two of docker env and my own local compute？ if i want to build a docker env of mmlspark， wish all the notebooks run well just likes the official image，How can I achieve this goal? any wiki or help doc for me？

**Comment by imatiach-msft** [comment]
hi @vinglogn "HDI cluster compute and local compute environment, and my problem is with the latter."
maybe there is some misunderstanding - there are two sets of notebooks, cluster and local, and it looks like you are running the cluster notebooks locally whereas you should be running the local notebooks instead.  When you build the code by running ./runme, the local notebooks should be in the folder:
<root>/mmlspark/BuildArtifacts/notebooks/local
There will be many .ipynb notebooks here that you can run.
I'm guessing you are running the notebooks under here instead:
<root>/mmlspark/BuildArtifacts/notebooks/hdinsight
The docker image uses the local notebooks.

**Comment by vinglogn** [comment]
I got it, thanks! @imatiach-msft
