### ISSUE TITLE
use lightGBM fail in windows.

### ISSUE THREAD

**Issue by iamheroDaniel** [Azure/mmlspark#460]
Could not load the native libraries because we encountered the following problems: no _lightgbm in java.library.path and Could not find resource /com/microsoft/ml/lightgbm/windows/x86_64/_lightgbm.dll in jar.

**Comment by iamheroDaniel** [comment]
> Could not load the native libraries because we encountered the following problems: no _lightgbm in java.library.path and Could not find resource /com/microsoft/ml/lightgbm/windows/x86_64/_lightgbm.dll in jar.

**Comment by debadridtt** [comment]
were you able to solve this? I'm having the same issue as well

**Comment by iamheroDaniel** [comment]
pip install mmlspark-0.15.dev2+1.g11ad24d-py2.py3-none-any.whl

and I suggest you use linux not windows. I can't run with windows, but liunx works well

**Comment by debadridtt** [comment]
oh, i'm trying it on windows actually!
