### ISSUE TITLE
LightGBM SHAP values

### ISSUE THREAD

**Issue by ekerazha** [Azure/mmlspark#468]
Although MMLSpark supports LIME for image classifiers interpretations, LightGBM natively supports SHAP (https://github.com/slundberg/shap) for models explanation.

See LightGBM's predict_contrib parameter: https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst

This is an important feature for LightGBM models explanation. Can SHAP values prediction be added to MMLSpark?

I think you could also use SHAP for image classifiers interpretations (instead of LIME). This is a LIME vs SHAP comparison (by the SHAP author): https://github.com/slundberg/shap/issues/19

**Comment by imatiach-msft** [comment]
@ekerazha I'm very familiar with shap as I've contributed to it before, I agree it would be nice to add a TreeExplainer to MMLSpark (not just for lightgbm but a more general one, eg which has support for SparkML models).  As a work-around for now, you could always export the LightGBM model to file, load it in python and then run shap's TreeExplainer on that.

**Comment by ekerazha** [comment]
@imatiach-msft 
Should I use `saveNativeModel()`? Is there a way to save the model to a string instead of a file? I see a `loadNativeModelFromString()` method but there isn't a "saveNativeModelToString" method.

**Comment by imatiach-msft** [comment]
@ekerazha are you in pyspark or scala?  If in scala, you can just do <your lightgbmmodel>.model.model to get the string.  There is no nice way to do it in python yet, we should add it, but for a quick hack <your python lightgbmmodel>._java_obj.model.model should work.

**Comment by ekerazha** [comment]
@imatiach-msft 
I'm in pyspark

**Comment by imatiach-msft** [comment]
@ekerazha does <your lightgbm model>._java_obj.model.model work for you?

**Comment by BrianMiner** [comment]
@imatiach-msft If we do `saveNativeModel` in pyspark, is this the same thing model object as would be produced from the python version of lightgbm, so it would work in Shap?

**Comment by candalfigomoro** [comment]
@imatiach-msft 
This PR https://github.com/Azure/mmlspark/pull/791 added `getFeatureShaps` to `LightGBMRanker`, maybe it should also be added to Classifier and Regressor.

**Comment by imatiach-msft** [comment]
closing as shap values support has been added to all models with PR https://github.com/Azure/mmlspark/pull/864
