### ISSUE TITLE
How to set boost_from_average in LightGBMClassifier?

### ISSUE THREAD

**Issue by PuZhang-github** [Azure/mmlspark#471]
I used --packages com.microsoft.ml.spark:mmlspark_2.11:0.15.dev2+1.g3ac4123 --repositories https://mmlspark.azureedge.net/maven 
I got the following result. I want to know how to set "boost_from_average" = False in my code?

[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499731 -> initscore=-0.001076
[LightGBM] [Info] Start training from score -0.001076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[Stage 10:>                                                         (0 + 1) / 1][LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

**Comment by imatiach-msft** [comment]
@PuZhang-github I'm guessing it won't help, but I can add the param to the learner - also, in the meantime, if your dataset is not confidential, would you be able to share it and I could take a look?

**Comment by PuZhang-github** [comment]
Sorry, the data is confidential. Can you please add the param to the learner. I want to try this parameter.

**Comment by imatiach-msft** [comment]
hi @PuZhang-github , I created a PR here yesterday to add the parameter:
https://github.com/Azure/mmlspark/pull/474
There is a build that you can use (not an official release yet, so you will need to specify the private repository):
```
Maven package uploaded, use --packages
com.microsoft.ml.spark:mmlspark_2.11:0.15.dev12+1.g9778c09
and --repositories
https://mmlspark.azureedge.net/maven
```
You will need to set the param to false instead of the default true.
Let me know if this helps resolve your issue!

**Comment by imatiach-msft** [comment]
@PuZhang-github sorry, did you have a chance to try out the fix?

**Comment by PuZhang-github** [comment]
Sorry for the long wait.  I still can not set this parameter. The following is my code.
model = LightGBMClassifier(featuresCol= 'features', labelCol = 'label', learningRate = 0.1, numIterations = 100,numLeaves=120,maxDepth=25,earlyStoppingRound=50,objective='binary',
                           baggingFraction=1.0,featureFraction=0.8,boost_from_average = False).fit(train)
 And I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/spark/python/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'boost_from_average'
