### ISSUE TITLE
select boosting type and transform function with pred_leaf

### ISSUE THREAD

**Issue by kunguang** [Azure/mmlspark#479]
![image](https://user-images.githubusercontent.com/3446934/51520921-f99c3080-1e5f-11e9-9522-004cdaa90450.png)
How do I use this function?

and i want predict like "bst.predict(testfile,pred_leaf=True)", use pred_leaf.

**Comment by Jie-Yuan** [comment]
and i want predict like "bst.predict(testfile,pred_leaf=True)", use pred_leaf.
