### ISSUE TITLE
Sample notebook link gives 404 Error

### ISSUE THREAD

**Issue by srib** [Azure/mmlspark#490]
The link to the [end-to-end](https://github.com/Azure/mmlspark/blob/master/notebooks/samples/106%20-%20Quantile%20Regression%20with%20LightGBM.ipynb) example in [this](https://github.com/Azure/mmlspark/blob/master/docs/lightgbm.md) page gives a 404 error.

The right link is [here](https://github.com/Azure/mmlspark/blob/master/notebooks/samples/LightGBM%20-%20Quantile%20Regression%20for%20Drug%20Discovery.ipynb).

I can send a PR if you prefer.

**Comment by drdarshan** [comment]
Dear @srib, thank you for the report, I sent a PR to fix the link. 

@mhamilton723 - could you please approve?

**Comment by drdarshan** [comment]
Closing.
