### ISSUE TITLE
the latest library (V0.15) from maven repository is not the same with the source code in github

### ISSUE THREAD

**Issue by wangdaiyin** [Azure/mmlspark#508]
the latest library (V0.15) from maven repository (url: https://mvnrepository.com/artifact/Azure/mmlspark/0.15) is not the same with the source code in github.
ex. some interfaces in class LightGBMClassifier, such as setBoostingType、setBoostFromAverage are available in the source code in github, but they don't exist in the latest library (V0.15)  from maven repository

**Comment by imatiach-msft** [comment]
@wangdaiyin closing as v0.16 has been released

**Comment by wangdaiyin** [comment]
OK，thanks
