### ISSUE TITLE
LightGBM not supported on mac OS yet. (MMLSPARK v0.16)

### ISSUE THREAD

**Issue by wxrui** [Azure/mmlspark#512]
19/03/09 14:31:29 INFO LightGBMRegressor: LightGBM worker got nodes for network init: 192.168.10.113:12400,192.168.10.113:12404
19/03/09 14:31:29 INFO LightGBMRegressor: LightGBM worker listening on: 12404
19/03/09 14:31:29 INFO LightGBMRegressor: LightGBM worker listening on: 12400
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12404...
[LightGBM] [Info] Binding port 12404 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Fatal] Socket send error, code: 32
libc++abi.dylib: terminating

**Comment by imatiach-msft** [comment]
@wxrui sorry, we don't support macOS with this release:
https://github.com/Azure/mmlspark/issues/290
Although we should support it with next one as we have merged in the changes to support it to LightGBM repo:
https://github.com/Microsoft/LightGBM/commit/414bb609c0d8c97091627a77ab49a1647825f1a9

**Comment by imatiach-msft** [comment]
closing as latest master now supports mac OS
