### ISSUE TITLE
Is there guide for scala saprk

### ISSUE THREAD

**Issue by Oukaishen** [Azure/mmlspark#527]
Hello, May I ask if there is any guide on How to include this as a jar into Spark scala project?

What I have done now is include the following in my pom

       <dependency>
            <groupId>Azure</groupId>
            <artifactId>mmlspark</artifactId>
            <version>0.16</version>
            <scope>provided</scope>
        </dependency>

is this just ok enough for me to use the spark "LightGBMClassifier" ? 

Question 2 is that this jar seems too large for me (~300Mb). Is the full jar needed for the LightGBM model?  Is there possible ways to shrink the size?

**Comment by mhamilton723** [comment]
Hey, that is indeed the right way to import though I am not sure about the provided tag for your case. Also, consider using dependency exclusions to exclude CNTK jar dependency which is the majority of the size. 

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by gypsysunny** [comment]
the jar is of 4 MB, isn't it? but the scala api is not compatible with the doc. say,  LightGBMClassifier doesn't have fit(). so don't know how to use it in scala.

**Comment by imatiach-msft** [comment]
@gypsysunny LightGBMClassifier does have a fit method, can you please point to the broken doc link?  thanks!
