### ISSUE TITLE
Increase Documentation on TabularLIME and LIME

### ISSUE THREAD

**Issue by phatak-dev** [Azure/mmlspark#529]
Hi,
Thanks for providing Spark native LIME implementation

Is there any documentation on getting information like *explain_instance* using this implementation.

Thank you

**Comment by mhamilton723** [comment]
Hey, Tabular Lime works very similar toImageLIME which is demonstrated here:

https://github.com/Azure/mmlspark/blob/master/notebooks/samples/ModelInterpretation%20-%20Snow%20Leopard%20Detection.ipynb

Also you can check out the examples in scala in the tests:
https://github.com/Azure/mmlspark/blob/master/src/image-featurizer/src/test/scala/LIMESuite.scala

**Comment by phatak-dev** [comment]
@mhamilton723 thanks for that. 

One more question, does current TabluarLIME handle categorical values?

**Comment by kiminh** [comment]
> @mhamilton723 thanks for that.
> 
> One more question, does current TabluarLIME handle categorical values?

Looking into the source code, it seems not able to handle categorical values.

**Comment by memoryz** [comment]
The latest LIME implementation in the `com.microsoft.ml.spark.explainers` package supports categorical features. https://github.com/Azure/mmlspark/blob/master/docs/explainers.md#TabularLIME
