### ISSUE TITLE
How to use the spark Serving with scala?

### ISSUE THREAD

**Issue by Herry-JWong** [Azure/mmlspark#534]
I use spark-shell --packages Azure:mmlspark:0.16 to open the scala prompt.
While i type import mmlspark, it is not work as i want.

scala> import mmlspark
     |
     |
You typed two blank lines.  Starting a new command.

scala>

So i couldn't call the function spark.readStream.server()

scala> spark.readStream.server()
<console>:27: error: value server is not a member of org.apache.spark.sql.streaming.DataStreamReader
       spark.readStream.server()

Thanks!

**Comment by mhamilton723** [comment]
you will need to import com.microsoft.ml.spark in scala land! similar to how pyspark -> org.apache.spark
