### ISSUE TITLE
LightGBM lambdarank not supported?

### ISSUE THREAD

**Issue by levyfan** [Azure/mmlspark#543]
Is lambdarank in LightGBM supported? I check the comment here and it says lambdarank is not supported. Is it in the development plan?

https://github.com/Azure/mmlspark/blob/d98b58b34b9a7f7690bee949283a098621ddfac3/src/lightgbm/src/main/scala/LightGBMParams.scala#L47

**Comment by imatiach-msft** [comment]
@levyfan unfortunately it is not supported yet, but I am planning to add this hopefully soon.  There is an issue here to track this work already:
https://github.com/Azure/mmlspark/issues/446
This is one of my top todo items.
