### ISSUE TITLE
why doesn't LightGBMClassifier in scala provide fit() as the api doc tells?

### ISSUE THREAD

**Issue by gypsysunny** [Azure/mmlspark#567]
the scala api doc includes "def fit(dataset: Dataset[_]): LightGBMClassificationModel" and some other functions, which are not provided by LightGBMClassifier when you are trying to use it. LightGBMClassifier.fit is always marked with red in intellij IDE that has involved the mmlspark jar. so how do we use the api in scala.

**Comment by imatiach-msft** [comment]
@gypsysunny sorry about the trouble you are having.  There should be a "fit" from Spark ML Predictor that calls train:
https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/Predictor.scala#L97

this is where it calls train:
https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/Predictor.scala#L118

train is defined in our mmlspark code base on the base class:
https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/main/scala/LightGBMBase.scala#L24

Are you sure you have the apache spark dependencies installed?  Also, are you trying to develop in the codebase or just use the package?  If the latter, you can just use the instructions in the main page.  If the former, we have a developers page here:
https://github.com/Azure/mmlspark/blob/master/docs/developer-readme.md

**Comment by imatiach-msft** [comment]
@gypsysunny closing this issue, please reopen if there are still problems with using LightGBMClassifier
