### ISSUE TITLE
LightGBMClassifier: for multiclass objective, wrong probability and prediction

### ISSUE THREAD

**Issue by sunilsu** [Azure/mmlspark#568]
Training a LightGBMClassifier with multiclass objective,
```
lgbm = LightGBMClassifier(objective='multiclass')
model = lgbm.fit(train)
scoredData = model.transform(test)


scoredData (raw and probability) looks like,
rawPrediction=DenseVector([-1.4917, -1.4697, -1.5847, -1.8326, -1.7148]),
probability=DenseVector([0.1837, 0.8163, -1.5847, -1.8326, -1.7148])
```
probability is still calculated as binary classification.
Maybe prediction column is also wrong because of above.

**Comment by imatiach-msft** [comment]
closing as this is now fixed with https://github.com/Azure/mmlspark/pull/578

latest build with fix:
Maven package uploaded, use --packages com.microsoft.ml.spark:mmlspark_2.11:0.17.dev21 and --repositories https://mmlspark.azureedge.net/maven

the fix should be available in the next v0.18 release
