### ISSUE TITLE
LightGBMRanker fails when the query column is not of type `Int`

### ISSUE THREAD

**Issue by daureg** [Azure/mmlspark#573]
I was playing with `LightGBMRanker` introduced in #554 and it took me a long time to understand why it refusing to train on some sample data. Somehow in my dataset, the query column was of type `long`, and calling the `fit` method (on Databricks) was resulting in 
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 118.0 failed 4 times, most recent failure: Lost task 2.3 in stage 118.0 (TID 500, 10.152.253.140, executor 1): java.net.ConnectException: Connection refused (Connection refused)
```

On my local Zeppelin, I got a more informative:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 10, localhost, executor driver): java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
```

The problem is thus the `getInt` call in [`TrainUtils.addGroupColumn`](https://github.com/Azure/mmlspark/blob/6a6d57f40ecd25a23efae29b2d18671647dbdb3f/src/lightgbm/src/main/scala/TrainUtils.scala#L64)

### steps to reproduce:

```
val dataset = spark.createDataFrame(Seq(
  (0L, 1, 1.2, 2.3),
  (0L, 0, 3.2, 2.35),
  (1L, 0, 1.72, 1.39),
  (1L, 1, 1.82, 3.8)
)).toDF("query", "label", "f1", "f2")
import org.apache.spark.ml.feature.VectorAssembler
import com.microsoft.ml.spark.LightGBMRanker
import org.apache.spark.sql.functions._

val assembler = new VectorAssembler().setInputCols(Array("f1", "f2")).setOutputCol("features")
val output = assembler.transform(dataset).select("query", "label", "features")
println(output.schema)
val lgbm = new LightGBMRanker()
  .setLabelCol("label")
  .setFeaturesCol("features")
  .setGroupCol("query")
  .setNumIterations(2)
```
prints ```StructType(StructField(query,LongType,false), StructField(label,IntegerType,false), StructField(features,org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7,true))```

and ```lgbm.fit(output)``` fails, while ```lgbm.fit(output.withColumn("query", col("query").cast("Int")))``` works

**Comment by imatiach-msft** [comment]
@daureg thank you for the repro.
It looks like lightgbm only support int column type:
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#group_column
But I think I can just do the conversion on the scala side before passing the data to lightgbm.

**Comment by imatiach-msft** [comment]
closing issue as fix in PR has been merged
