### ISSUE TITLE
Illegal characters in column names in SummarizeData

### ISSUE THREAD

**Issue by SemyonSinchenko** [Azure/mmlspark#585]
When I use the SummarizeData transformer and try to save results in parquet I get an error from org.apache.parquet.ParquetOutputCommitter:
`Exception in thread "main" org.apache.spark.sql.AnalysisException: Attribute name "Unique Value Counts" contains invalid character(s) among " ,;{}()\n\t=". Please use alias to rename it.;`

By using of `foldLeft` I can replace all spaces by "_" but it seems that that behavior is not obvious and can be fixed by simple renaming of columns in source code: https://github.com/Azure/mmlspark/blob/44735200184151e180a3188fa315fa15a7fd18fa/src/summarize-data/src/main/scala/SummarizeData.scala#L203-L235

**Comment by imatiach-msft** [comment]
@SemyonSinchenko thank you for finding this issue, I've created a PR to fix it by using _
#587
