### ISSUE TITLE
LightGBMRanker (pyspark): labelGain parameter default causes error [minor issue]

### ISSUE THREAD

**Issue by tyler-romero** [Azure/mmlspark#595]
Running LightGBMRanker without labelGain set causes an error:

> java.lang.ClassCastException: java.lang.String cannot be cast to [D

Running `inspect.signature(LightGBMRanker)`, I see:

> Signature (baggingFraction=1.0, baggingFreq=0, baggingSeed=3, boostFromAverage=True, boostingType='gbdt', categoricalSlotIndexes=None, categoricalSlotNames=None, defaultListenPort=12400, earlyStoppingRound=0, featureFraction=1.0, featuresCol='features', groupCol=None, initScoreCol=None, isProvideTrainingMetric=False, labelCol='label', labelGain='[]', lambdaL1=0.0, lambdaL2=0.0, learningRate=0.1, maxBin=255, maxDepth=-1, maxPosition=20, minSumHessianInLeaf=0.001, modelString='', numBatches=0, numIterations=100, numLeaves=31, objective='lambdarank', parallelism='data_parallel', predictionCol='prediction', timeout=1200.0, validationIndicatorCol=None, verbosity=1, weightCol=None)

Setting the labelGain parameter to `labelGain=[]` rather than `labelGain='[]'` bypasses this error.

**Comment by imatiach-msft** [comment]
@tyler-romero thanks for finding this!  it looks like a bug in the python and sparklyr wrapper generators.

**Comment by imatiach-msft** [comment]
closing as this has been fixed with PR #598 and should be available in the next v0.18 release.
