### ISSUE TITLE
LightGBM saveNativeModel() not writing file on Databricks

### ISSUE THREAD

**Issue by tyler-romero** [Azure/mmlspark#599]
After successfully training a LightGBMClassifier or LightGBMRanker as the last stage in an MLLib pipeline, and trying to save the native model out to dbfs using this command:

`model.stages[-1].saveNativeModel('/dbfs/tmp/lightgbmNativeTemp.model')`

The file never gets written. Any idea why this might be happening?

**Comment by imatiach-msft** [comment]
@tyler-romero isn't that a local url?  For dbfs I believe you need to specify dbfs://...

**Comment by imatiach-msft** [comment]
eg see: https://docs.databricks.com/user-guide/dbfs-databricks-file-system.html

we just create a dataset and save it using the spark API:
https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/main/scala/LightGBMBooster.scala#L112

If you ran this scala code, where would the file get saved?

```
val rdd = session.sparkContext.parallelize(Seq("testing saving some text somewhere..."))
import session.sqlContext.implicits._
val dataset = session.sqlContext.createDataset(rdd)
val mode = SaveMode.Overwrite
dataset.coalesce(1).write.mode(mode).text(filename)
```

**Comment by tyler-romero** [comment]
Oh yeah, you're right! Using `dbfs:/tmp/lightgbmNativeTemp.model` worked. Thanks!
