### ISSUE TITLE
How to train model with  Scala TrainClassifier?

### ISSUE THREAD

**Issue by Jie-Yuan** [Azure/mmlspark#635]
val tc = new TrainClassifier("mmlsparkDemo")
    tc.setModel(LogisticRegression())
    tc.setLabelCol("label")

    val model = tc.fit(data)
    model.transform(data).show()

**Comment by Jie-Yuan** [comment]
Error:(31, 35) org.apache.spark.ml.classification.LogisticRegression.type does not take parameters
    tc.setModel(LogisticRegression())

**Comment by mhamilton723** [comment]
Hey, for more detailed usage check our tests, but it should look like: 

```scala
val tc = new TrainClassifier()
      .setModel(new LogisticRegression())
      .setFeaturesCol(YOUR_FEATURES_COL)
      .fit(df).transform(df)
```
