### ISSUE TITLE
Feature Request: Sparse Vector Support for LIME

### ISSUE THREAD

**Issue by mathew5** [Azure/mmlspark#648]
I am trying to explain the predictions made by my XGboost model using MMLSparks Lime package for scala. This is my first time using LIME library, I am able to perform a fit operation on the dataset and when I am trying to perform the transform operation, the program stops with an exception, "Caused by: java.lang.ClassCastException: org.apache.spark.ml.linalg.SparseVector cannot be cast to org.apache.spark.ml.linalg.DenseVector"Link to Error Log -1
![1](https://user-images.githubusercontent.com/43140278/63062082-7c193a00-beef-11e9-894f-ae8c7959bd2d.jpeg)
![2](https://user-images.githubusercontent.com/43140278/63062087-7f142a80-beef-11e9-8e0d-2faaede54001.jpeg)

**Comment by memoryz** [comment]
The latest LIME implementation in the explainers package should support explaining sparse vector output.
