### ISSUE TITLE
Categorical features not being used correctly by the LightGBM classification model.

### ISSUE THREAD

**Issue by telmoluismarques** [Azure/mmlspark#665]
**Describe the bug**

We are trying to migrate a setup of LightGBM running locally to MMLSpark. When running the final validations on a dataset we are familiar with we got some discrepancies in results between the local LightGBM model and the MMLSpark LightGBM model. 

This seems to arise from the fact that MMLSpark is not using the categorical features  as categoricals for the model. These findings are based on:
- If we retrain the local LightGBM model with the categorical (indexed) features as numericals the results match those of MMLSpark LightGBM Model
 - In the model trained locally we see num_cat > 0 on each tree as seen below
`Tree=199
num_leaves=50
num_cat=42
split_feature=190 29 207 87 200 228 200 201 228 201 224 201 199 225 224 199 199 13 217 225 199 217 228 224 224 203 31 226 157 225 228 228 201 6 225 224 259 228 259 224 228 201 203 224 203 228 203 228 224`
- In the MMLSpark model we see num_cat always equals to 0 on each tree as seen below
`Tree=199
num_leaves=50
num_cat=0
split_feature=188 250 117 200 240 0 199 227 193 10 202 111 27 251 87 217 25 199 259 186 187 148 173 250 0 248 219 206 79 224 223 198 119 212 29 111 218 225 208 250 199 187 4 217 217 41 259 228 203`

- Nevertheless, when we open the LightGBM model file, trained with MMLSpark, we see that the categorical indexes are correctly populated in the model parameters as seen below
`[categorical_feature: 198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259]`

It seems that although the model is receiving the correct categorical indexes, it is not using those to train those features as categoricals, taking a toll on model performance.

**To Reproduce**

1. Loaded a csv dataset into a dataframe, this dataset consists of numerical features (doubles) and categorical features (integers, indexed)
`dataset = spark.read.csv(filepath, header=True, inferSchema=True)`

2. Create the Spark vectorAssembler
```
assembler = VectorAssembler(
    inputCols = numerical_features + categorical_list_indexed,
    outputCol="features",
    handleInvalid="skip")
```

3. Transform the initial dataset to produce the features vector
```
output = assembler.transform(dataset)
train = output.select("features", "label")
```

4. Create the LightGBMClassifier, fit the training set and save the model to HDFS
```
model = LightGBMClassifier(numLeaves=50, maxBin=50, learningRate=0.01, numIterations=200, categoricalSlotNames=categorical_list_indexed)

model_obj = model.fit(train)

model_obj.saveNativeModel('test_model')
```

After this we would evaluate the predictions and open the model file in disk where we had the findings presented on the bug description

**Info (please complete the following information):**
 - MMLSpark Version: v0.17
 - Spark Version 2.4.3
 - Running on a Cloudera cluster

**Comment by imatiach-msft** [comment]
@telmoluismarques sorry, in the code above what is categorical_list_indexed?  If those are indexes make sure to use categoricalSlotIndexes instead of categoricalSlotNames.

**Comment by telmoluismarques** [comment]
`categorical_list_indexed` is a python list with the categorical feature names. We've validated those are being mapped correctly internally by LightGBM as the list of indexes that then shows up in the model .txt saved to disk, shown below, corresponds to the correct indexes in the feature vector:
`[categorical_feature: 198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259]`

**Comment by tyler-romero** [comment]
I had not noticed before, but I see the same problem when training `LightGBMRanker` models.

**Comment by imatiach-msft** [comment]
thanks @telmoluismarques and @tyler-romero for reporting the issue, sent PR here:
https://github.com/Azure/mmlspark/pull/685
it looks like the categorical indexes need to be on the dataset instead of the booster parameters for lightgbm.  I've opened a doc defect for lightgbm repo as well to clear up which parameters belong where.

**Comment by imatiach-msft** [comment]
@telmoluismarques @tyler-romero closing as fix has been merged
https://github.com/Azure/mmlspark/pull/685

**Comment by pedromcvaz** [comment]
Hi! Is this fix in the latest release? If not can you give me a version of the code with this fix?
