### ISSUE TITLE
LightGBMRanker with ValidationIndicatorCol: is the metric validated only up to @5?

### ISSUE THREAD

**Issue by catenamatteo** [Azure/mmlspark#697]
Hello,
I'm using `LightGBMRanker` with `ValidationIndicatorCol` to enable `earlyStopping`. From the logs, I can see that ndcg is evaluated up to the 5th position, even if i use `.setMaxPosition(10)`.
This is what I see:
```
2019-09-27 15:37:29 INFO  LightGBMRanker:212 - Valid ndcg@1=0.5995674734206613
2019-09-27 15:37:29 INFO  LightGBMRanker:212 - Valid ndcg@2=0.6006100821389552
2019-09-27 15:37:29 INFO  LightGBMRanker:212 - Valid ndcg@3=0.5948781960139197
2019-09-27 15:37:29 INFO  LightGBMRanker:212 - Valid ndcg@4=0.5992964390181633
2019-09-27 15:37:29 INFO  LightGBMRanker:212 - Valid ndcg@5=0.6006352154720541
```
Is the log's output somehow truncated, or is ndcg evaluated indeed only up to 5th position? Is there a way to change this behavior so that ndcg in validation is evaluated as per `.setMaxPosition()`?

**Comment by imatiach-msft** [comment]
@catenamatteo sorry about the trouble you are having.  I just took a look at this issue and I believe that this is the wrong parameter, please see eval_at parameter instead:
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#eval_at
the default is 1,2,3,4,5
Please let me know if you are still having trouble specifying the NDCG positions and reopen the issue, closing it for now.

**Comment by catenamatteo** [comment]
How can I set eval_at from Scala+Spark? I couldn't find a way, currently. I
saw the method is now implemented in the master branch, but it is not yet
released

Il mer 9 ott 2019, 05:42 Ilya Matiach <notifications@github.com> ha scritto:

**Comment by imatiach-msft** [comment]
@catenamatteo that's correct, this issue is only fixed on master - adding @mhamilton723 for release timeline, I believe we will have a new release soon
