### ISSUE TITLE
"port out of range error" when training

### ISSUE THREAD

**Issue by ibnopcit** [Azure/mmlspark#719]
Hi, I sporadically get the following error when training a LightGBMClassifier on YARN (with varying port numbers):

```
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 38 in stage 218.0 failed 1 times, most recent failure: Lost task 38.0 in stage 218.0 (TID 22099, gsbl427n05.wherever.com, executor 754): java.lang.IllegalArgumentException: port out of range:66688
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:166)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.findOpenPort(TrainUtils.scala:292)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.trainLightGBM(TrainUtils.scala:392)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188
```

I notice the code computes the port number by adding an executor or partition id to a default, but there is no bounds check on the result:

https://github.com/Azure/mmlspark/blob/f22aa732960abdd5c4db00a0d25b88b86b5c28fa/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L260

Should this be mod 65536?

**Comment by imatiach-msft** [comment]
@ibnopcit sorry about the issue you are encountering.  How many workers do you have?  The default listen port starts at 12400, which seems very reasonable:
 https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala#L9
maybe you have a lot of ports blocked off from access?

**Comment by ibnopcit** [comment]
Only about 10, but I'm on a big shared cluster.

**Comment by imatiach-msft** [comment]
hmm that does seem like a mystery, not sure why so many ports would be blocked off.  perhaps there is some firewall rule in place on the cluster.  I'm guessing you didn't specify a default port when running lightgbm in the parameters?  If not, then I'm not quite sure how to address this issue.

**Comment by ibnopcit** [comment]
If nothing else, shouldn't the calculated port be capped at 2^16?

**Comment by imatiach-msft** [comment]
@ibnopcit great idea, we can cap it and throw an exception once we get to the limit.  I'm still a bit confused as to how so many ports could be blocked on your cluster though.  Seems like a real edge-case scenario.

**Comment by imatiach-msft** [comment]
closing as this has been fixed in latest to have a cap on max allowed port, see PR
https://github.com/Azure/mmlspark/pull/759
