### ISSUE TITLE
Add dump_model in scala/spark too, to save model in json format

### ISSUE THREAD

**Issue by catenamatteo** [Azure/mmlspark#720]
lightgbm models trained in spark can be saved in their native format. However, such format is not very human-friendly nor easy to parse. the python wrapper of lightgbm has a dump_model method which convert the model into a json format. Would it be possible to have the same functionality in the scala/spark wrapper?

**Comment by imatiach-msft** [comment]
@catenamatteo that sounds like a good enhancement to have, great idea.

**Comment by imatiach-msft** [comment]
closing as associated PR has been merged to master
https://github.com/Azure/mmlspark/pull/730
