### ISSUE TITLE
Set Prediction / Feature / Label Column Names on Model

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [Azure/mmlspark#721]
**Is your feature request related to a problem? Please describe.**
When predicting scores with the `LightGBMRankerModel` in pyspark it would be nice to be able to change the input/output/label columns. This is useful when evaluating several models on the same dataframe

This probably applies to all the model types not just `LightGBMRankerModel`, thats just the one I'm working with.

Currently there is a work around, its just kinda ugly as you need to interact with the underlying java object.

```python
model._java_obj.setPredictionCol('alternate_prediction')
model._java_obj.setFeaturesCol('alternate_features')
model._java_obj.setLabelCol('alternate_label')
```

**Describe the solution you'd like**

The methods should exist on the python model class

```python
model.setPredictionCol('alternate_prediction')
model.setFeaturesCol('alternate_features')
model.setLabelCol('alternate_label')
```

**Comment by statgirl30** [comment]
Do we have to run vector assembler before passing the features to model.fit? I still cannot run the gbmlight from mmlspark package on Databricks

**Comment by imatiach-msft** [comment]
it seems this issue has already been resolved with the recent python code gen refactor
