### ISSUE TITLE
I want predict like "bst.predict(testfile,pred_leaf=True)", use pred_leaf.

### ISSUE THREAD

**Issue by Jie-Yuan** [Azure/mmlspark#724]
I want predict like "bst.predict(testfile,pred_leaf=True)", use pred_leaf.

**Comment by Jie-Yuan** [comment]
pred_leaf

**Comment by Jie-Yuan** [comment]
pred_leaf！！！thanks

**Comment by Jie-Yuan** [comment]
How to get the tree node index

**Comment by Jie-Yuan** [comment]
> I want predict like "bst.predict(testfile,pred_leaf=True)", use pred_leaf.

How to get the tree node index？

**Comment by Jie-Yuan** [comment]
predict leaf index

**Comment by Jie-Yuan** [comment]
the predicted leaf every tree for each sample.

**Comment by imatiach-msft** [comment]
hi @Jie-Yuan sorry about the trouble you are having.  This feature is not available yet, however, I think it should be straightforward to add.  I will look into adding it.

**Comment by imatiach-msft** [comment]
we could add something similar to the python API that would be passed down to the prediction function:
https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L616
maybe have it as a parameter on the model

**Comment by JWenBin** [comment]
o(╯□╰)o, the same with me

**Comment by imatiach-msft** [comment]
you can now call "setLeafPredictionCol", which will output pred leaf as an additional column on predict
