### ISSUE TITLE
(Question) Estimation of Model In Pyspark Versus Python

### ISSUE THREAD

**Issue by allard-jeff** [Azure/mmlspark#742]
If I fit a LightGBMClassifier and then predict a small number of instances, I see the following predictions (of the positive class):

![image](https://user-images.githubusercontent.com/43180588/68987970-f8c4f880-07fd-11ea-914b-a96e2953096e.png)

If I save the model via `saveNativeModel` and load into python lightgbm via `lgb.Booster(model_file=)` and run inference on the same instances (these were ran through the same pipeline as the pyspark prediction prior to being transformed to Pandas) the estimates are close...but not the same:

![image](https://user-images.githubusercontent.com/43180588/68988028-02029500-07ff-11ea-8c10-9ef5325390aa.png)

Is this to be expected between Spark and Python of the same model?

**Comment by imatiach-msft** [comment]
@allard-jeff great find, supposedly those values should be the same.  I'm not sure why they are different. Are you sure the input values in pandas are the same as in spark when doing the comparison?  Will leave this defect open for now for investigation.  It might help to post a small repro of the issue.

**Comment by imatiach-msft** [comment]
also, what is your python lightgbm version?  I wonder if any version mismatch might cause something like this.

**Comment by allard-jeff** [comment]
It might be an issue with versions. I updated lightgbm via pip and after working out a full reproducible example to share...they match! I will close and re-open if I see this issue again.
