### ISSUE TITLE
Missing lightgbm learning parameter - min_data_in_leaf

### ISSUE THREAD

**Issue by louis925** [Azure/mmlspark#746]
The MMLSpark version of LightGBMseems seems to miss the parameter `min_data_in_leaf`, which is actually an important learning parameter in LightGBM
 https://lightgbm.readthedocs.io/en/latest/Parameters.html#min_data_in_leaf

While tracing the source code, I was not able to find it in
https://github.com/Azure/mmlspark/blob/8bb7d861981fd519d4623cc903cbe9919762cb3f/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala

I was wondering why mmlspark didn't have this parameter, and what is the default value used by the underlying lightgbm if it was not set by the mmlspark?

**Comment by RefiPeretz** [comment]
I'm not a developer but I had the same problem. They didn't implement all possible parameters to LightGBM for me it was to clone add it myself and compile my own version.

**Comment by imatiach-msft** [comment]
closing as this parameter has been added in latest, see
https://github.com/Azure/mmlspark/pull/760

**Comment by eromoe** [comment]
![image](https://user-images.githubusercontent.com/3938751/89245605-c1bc9e80-d63b-11ea-9a30-42f15a076168.png)

rc1.0.0 doesn't contain this .
