### ISSUE TITLE
Make CNTKModel support Multi-in Multi-out models

### ISSUE THREAD

**Issue by mhamilton723** [Azure/mmlspark#75]
- right now it only supports single in single out

**Comment by thdeltei** [comment]
Does this mean that currently I couldn't have a model that say, has 50 sigmoids on the last layer to do multi label classication?

**Comment by rastala** [comment]
In the multi-label case, if you have access to the CNTK model, you could manually splice the outputs into single vector on CNTK side, and then split them apart on Spark side. However, doing this manually in both training and scoring workflow is not very convenient.

**Comment by mhamilton723** [comment]
@thdeltei I think your use case is fully supported. What I mean by this is multi-vector ins and outs. A input/output that has shape (50) is completely supported. What is not supported are models that require 2 different tensor inputs or outputs. This is common in multi-task learning, but uncommon in most classification/regression setups.

**Comment by mhamilton723** [comment]
Just merged!
