### ISSUE TITLE
Support getting best_iteration from trained lgb models

### ISSUE THREAD

**Issue by zijie0** [Azure/mmlspark#775]
Currently, we can set earlyStoppingRound when training a lightGBM model. However, when the training is finished, we could not get best_iteration information as the native lgb library. 
Could we support getting that information so we can further train a new model with all the train & validation data. Or there's any workaround?

Thanks.

**Comment by imatiach-msft** [comment]
closing as this has been fixed with https://github.com/Azure/mmlspark/pull/1024
