### ISSUE TITLE
metric option in mmlspark LightGBMClassifier

### ISSUE THREAD

**Issue by devilwing0723** [Azure/mmlspark#787]
I am trying to use the "metric" option in mmlspark LightGBMClassifier. This option is available in the local version of lightgbm, and it seems to be available in mmlspark version based on what I see in the following link.

https://github.com/Azure/mmlspark/blob/f3d624dbd3b15b64061ab8fb9b4a3f6a61f35f99/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala

But when I tried to run the following code it gave me an error saying " __init__() got an unexpected keyword argument 'metric'". I don't know why this is the case. Does this indicate this option isn't available in the current version or is it a bug?

from mmlspark.lightgbm import LightGBMClassifier
lgbm = LightGBMClassifier(objective = "binary",
                           featuresCol = "features",
                           labelCol = "g_dr_co",
                           numIterations=10,
                           numLeaves=31,
                           isUnbalance=False,
                           verbosity=10,
                           parallelism='data_parallel',
                           timeout=1200.0,
                           maxBin = 200,
                           useBarrierExecutionMode=False,
                           metric="binary_logloss",
                           defaultListenPort=9000)

**Comment by imatiach-msft** [comment]
@devilwing0723 what version of mmlspark are you using?  I believe you are correct, this probably indicates you are using an older version that doesn't have this parameter.

The parameter is available here:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala#L259

**Comment by imatiach-msft** [comment]
closing as this parameter has been available for several releases now
