### ISSUE TITLE
Regression: Including column names when saving LightGBM native model?

### ISSUE THREAD

**Issue by tyler-romero** [Azure/mmlspark#806]
I'm having the same issue as described here: https://github.com/Azure/mmlspark/issues/332

It seems there was a PR to resolve this issue, and it has worked for me in the past. But since updating to 0.81 and 1.0, I have been encountering this again (I encounter it in both versions).

I am using PySpark on Databricks. Installed mmlspark using the instructions in the Readme.

My training setup involves fitting a LightGBMClassifier inside of a spark pipeline.

**Comment by imatiach-msft** [comment]
@tyler-romero might you have sparse data?  Also, are you relying on the slot names from the vector column on the DataFrame getting passed over to the native dataset representation or are you manually passing in the slot names via the parameter (https://github.com/Azure/mmlspark/blob/e745784c7e60a07652bfc24e3039ed5906754541/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala#L101)?

**Comment by tyler-romero** [comment]
My data may be sparse after VectorAssembler, but at that point in my pipeline I apply this transformation:

```python
toDenseUdf = F.udf(lambda v: Vectors.dense(v.toArray()), VectorUDT())
class VectorDensifier(Transformer, HasInputCol, HasOutputCol):
    @keyword_only
    def __init__(self, inputCol=None, outputCol=None):
        super(VectorDensifier, self).__init__()
        kwargs = self._input_kwargs
        self.setParams(**kwargs)

    @keyword_only
    def setParams(self, inputCol=None, outputCol=None):
        kwargs = self._input_kwargs
        return self._set(**kwargs)

    def _transform(self, dataset):
        return dataset.withColumn(self.getOutputCol(), toDenseUdf(self.getInputCol()))
```

I'm not manually passing the slot names. I dont see that option available in the python bindings, when I run (v1.0.0):
```
inspect.signature(LightGBMClassifier)
```
I see:
```
<Signature (baggingFraction=1.0, baggingFreq=0, baggingSeed=3, boostFromAverage=True, boostingType='gbdt', categoricalSlotIndexes=None, categoricalSlotNames=None, defaultListenPort=12400, earlyStoppingRound=0, featureFraction=1.0, featuresCol='features', initScoreCol=None, isProvideTrainingMetric=False, isUnbalance=False, labelCol='label', lambdaL1=0.0, lambdaL2=0.0, learningRate=0.1, maxBin=255, maxDepth=-1, metric='', minSumHessianInLeaf=0.001, modelString='', numBatches=0, numIterations=100, numLeaves=31, objective='binary', parallelism='data_parallel', predictionCol='prediction', probabilityCol='probability', rawPredictionCol='rawPrediction', thresholds=None, timeout=1200.0, useBarrierExecutionMode=False, validationIndicatorCol=None, verbosity=1, weightCol=None)>
```

No mention of a slot names parameter. Didn't see anything in the python documentation either.

**Comment by imatiach-msft** [comment]
@tyler-romero sorry, the slotnames parameter was added back in December:
https://github.com/Azure/mmlspark/pull/752
1.0 release was from back in October, so it makes sense that you wouldn't have it

**Comment by imatiach-msft** [comment]
ok, so it looks like you are just not passing the metadata on the DataFrame through which contains the slot names, which is why it is missing after the VectorDensifier

**Comment by tyler-romero** [comment]
How can I get a build with the slot names parameter added?

**Comment by imatiach-msft** [comment]
several options, you could use the daily build on the main webpage:
![image](https://user-images.githubusercontent.com/24683184/75561794-917e2d80-5a15-11ea-91c6-20503767581a.png)

or, I'm not sure if you have access to the devops, you can get the build from each PR (either on master or individual build)

You will need to just specify the resolver below to use that build (which points to an azure blob storage location):

https://mmlspark.azureedge.net/maven

**Comment by imatiach-msft** [comment]
also adding @mhamilton723 for timeline on next mmlspark release

**Comment by tyler-romero** [comment]
Thanks! Missed that version on the main webpage. Thanks!
