### ISSUE TITLE
Download newest version jar

### ISSUE THREAD

**Issue by ce39906** [Azure/mmlspark#818]
**Is your feature request related to a problem? Please describe.**
Our spark cluster can only connect to the internal network, so i want to download the newest jar and upload it to our server.
**Describe the solution you'd like**
get the the com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1 jar

**Comment by imatiach-msft** [comment]
@ce39906 you may be able to use the following command to get the jar:

```
mvn dependency:get -DremoteRepositories="https://mmlspark.azureedge.net/maven" -Dartifact="com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1" -Ddest=.
```

hope this helps!

**Comment by ce39906** [comment]
> @ce39906 you may be able to use the following command to get the jar:
> 
> ```
> mvn dependency:get -DremoteRepositories="https://mmlspark.azureedge.net/maven" -Dartifact="com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1" -Ddest=.
> ```
> 
> hope this helps!
Thanks for your reply, I got an error like this
![image](https://user-images.githubusercontent.com/10767336/76191314-0ae9fd00-621a-11ea-8fe4-7d5005d60e71.png)

**Comment by ce39906** [comment]
> https://mmlspark.azureedge.net/maven

@imatiach-msft ，This address seems to have expired
![image](https://user-images.githubusercontent.com/10767336/76380106-ee220680-638c-11ea-85a2-2a101822cd5a.png)

**Comment by imatiach-msft** [comment]
@ce39906 it's definitely not expired, you just can't view it in the browser like that.  I'm not sure why you are getting the error above though.

**Comment by imatiach-msft** [comment]
interesting, in the error I see jar between mmlspark_2.11 and 1.0.0-rc1, I wonder if the path is wrong - can you paste the command you ran too (it should just be the one I sent?)

com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1

**Comment by ce39906** [comment]
> interesting, in the error I see jar between mmlspark_2.11 and 1.0.0-rc1, I wonder if the path is wrong - can you paste the command you ran too (it should just be the one I sent?)
> 
> com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1

![image](https://user-images.githubusercontent.com/10767336/76387656-6810ba80-63a2-11ea-92a8-22c5086e0727.png)

**Comment by imatiach-msft** [comment]
hmm worked fine for me:

![image](https://user-images.githubusercontent.com/24683184/76461883-19215000-63b7-11ea-8901-c3f7ceb6d2fb.png)

**Comment by imatiach-msft** [comment]
it looks like it copied it from .m2 folder that time though, let me try with that file removed

**Comment by imatiach-msft** [comment]
![image](https://user-images.githubusercontent.com/24683184/76462155-95b42e80-63b7-11ea-839a-e62edc4bf992.png)

**Comment by imatiach-msft** [comment]
https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.11/1.0.0-rc1/mmlspark_2.11-1.0.0-rc1.jar

https://repo.maven.apache.org/maven2/com/microsoft/ml/lightgbm/lightgbmlib/2.3.100/lightgbmlib-2.3.100.jar

**Comment by imatiach-msft** [comment]
@ce39906 can you try those two links?

**Comment by ce39906** [comment]
> @ce39906 can you try those two links?

Thanks a lot, those two links worked!
