### ISSUE TITLE
Save and load model using FindBestModel

### ISSUE THREAD

**Issue by thdeltei** [Azure/mmlspark#83]
How do I save and load the best model found using FindBestModel?

```
best_model = FindBestModel(evaluationMetric="AUC", models=lrmodels).fit(test)
best_model.write().overwrite().save('model.mml')
loaded_best_model = mmlspark.BestModel.load('model.mml')
```

`loaded_best_model` doesn't seem to be a sparkML model, it has a `.getModels()` method which fails when called and no transform() method.

**Comment by imatiach-msft** [comment]
This is a defect, this should be fixed with this PR:
https://github.com/Azure/mmlspark/pull/84

**Comment by imatiach-msft** [comment]
The issue should be fixed now, thank you for reporting it.
