### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by dciborow** [Azure/mmlspark#843]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, code snippets encouraged

**Expected behavior**

**Info (please complete the following information):**
 - MMLSpark Version: [e.g. v0.17]
 - Spark Version [e.g. 2.4.3]
 - Spark Platform [e.g. Databricks]

** Stacktrace**
```
Please post the stacktrace here if applicable
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by dciborow** [comment]
@dciborow

**Comment by imatiach-msft** [comment]
closing this test issue
