### ISSUE TITLE
Maven Dependency

### ISSUE THREAD

**Issue by KlausSchaefersAtWork** [Azure/mmlspark#85]
I added the following dep to my poml.xml

  <dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark</artifactId>
            <version>0.6</version>
            <scope>test</scope>
        </dependency>

and also added the repo

 <repositories>
        <repository>
            <id>azureedge.net</id>
            <name>MS Azure Maven Repo</name>
            <url>https://mmlspark.azureedge.net/maven</url>
        </repository>
    </repositories>

Still maven cannot find the artifact...

**Comment by drdarshan** [comment]
Dear @KlausSchaefersAtWork, thanks for reporting this - I'll take a look right away.

**Comment by drdarshan** [comment]
Dear @KlausSchaefersAtWork, it is possibly an issue with the CDN on our side. 

Could you please try the instructions to get it working via SBT [here](https://github.com/Azure/mmlspark#sbt)? I just tried a simple program and it worked for me. 

Also, if you are able to attach your POM file, we can look into it more.

Sorry for the inconvenience and thanks for your patience while we figure this out!

**Comment by elibarzilay** [comment]
@KlausSchaefersAtWork -- have you tried the above?

**Comment by KlausSchaefersAtWork** [comment]
Hi,

I took the latest dependency from maven central...

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.quant-ux</groupId>
    <artifactId>spark-example</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.11</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.11</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>Azure</groupId>
            <artifactId>mmlspark</artifactId>
            <version>0.6</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <repositories>
        <repository>
            <id>azureedge.net</id>
            <name>MS Azure Maven Repo</name>
            <url>https://mmlspark.azureedge.net/maven</url>
        </repository>
    </repositories>


</project>

**Comment by imatiach-msft** [comment]
I don't believe 0.6 version exists, see here:
https://mvnrepository.com/artifact/Azure/mmlspark
The latest version is 0.9, so I would recommend using that:
https://mvnrepository.com/artifact/Azure/mmlspark/0.9

**Comment by imatiach-msft** [comment]
@KlausSchaefersAtWork can you try my suggestion and let us know if the newer version in maven central works for you?

**Comment by elibarzilay** [comment]
I'm not sure what's wrong exactly, but in general, we have no early packages (definitely not 0.6) on maven central itself, I think that it went on there later as part of the spark package uploads.  But if you're specifying our maven url as a repository, then it should exist there.

**Comment by elibarzilay** [comment]
Something that came up now when @mhamilton723 was entering the coordinates of a build: the artifact id for the maven coordinates should be `mmlspark_2.11`.

**Comment by mhamilton723** [comment]
@elibarzilay can this be closed?

**Comment by elibarzilay** [comment]
Likely stale.

**Comment by friyal** [comment]
Hello, I use the following pom.xml:
<repository>
            <id>azureedge.net</id>
            <name>MS Azure Maven Repo</name>
            <url>https://mmlspark.azureedge.net/maven</url>
</repository>
<dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark_2.11</artifactId>
            <version>0.13</version>
</dependency>

But there is an error when I was trying to run it in spark:

Downloading: 
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/com/microsoft/ml/spark/mmlspark_2.11/0.13/mmlspark_2.11-0.13.pom
Downloading: http://packages.confluent.io/maven/com/microsoft/ml/spark/mmlspark_2.11/0.13/mmlspark_2.11-0.13.pom
Downloading: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.11/0.13/mmlspark_2.11-0.13.pom
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://mmlspark.azureedge.net:443: Connection reset
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://mmlspark.azureedge.net:443
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://mmlspark.azureedge.net:443: Connection reset
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://mmlspark.azureedge.net:443
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://mmlspark.azureedge.net:443: Connection reset
Aug 22, 2018 1:26:52 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://mmlspark.azureedge.net:443
Downloading: https://repo.maven.apache.org/maven2/com/microsoft/ml/spark/mmlspark_2.11/0.13/mmlspark_2.11-0.13.pom
[ERROR] Failed to execute goal on project XXX: Could not resolve dependencies for project XXX:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.microsoft.ml.spark:mmlspark_2.11:jar:0.13: Failed to read artifact descriptor for com.microsoft.ml.spark:mmlspark_2.11:jar:0.13: Could not transfer artifact com.microsoft.ml.spark:mmlspark_2.11:pom:0.13 from/to azureedge.net (https://mmlspark.azureedge.net/maven): Connection reset -> [Help 1]

And I found that nowhere exists required pom file. May I know how I can use the mmlspark in my project?

**Comment by imatiach-msft** [comment]
You can get mmlspark from maven central, eg:
https://mvnrepository.com/artifact/Azure/mmlspark/0.13

So this is what it would look like:


<dependency>
    <groupId>Azure</groupId>
    <artifactId>mmlspark</artifactId>
    <version>0.13</version>
</dependency>

Thank you, Ilya

**Comment by imatiach-msft** [comment]
This is still using mmlspark repo instead of maven central.  Could you use maven central instead?  Also, I’m not sure why, but your comments are not appearing on github, strange.
Thank you, Ilya

**Comment by friyal** [comment]
Hello, I've solved the problem by using something like:
<repository>
     <id>Maven</id>
     <url>https://dl.bintray.com/spark-packages/maven/</url>
</repository>
<dependency>
      <groupId>Azure</groupId>
      <artifactId>mmlspark</artifactId>
     <version>0.13</version>
</dependency>
I think I just took a wrong repository before. 
Thank you very much!

**Comment by imatiach-msft** [comment]
Yes, that looks better, glad you were able to find it.  The package is on maven central as well so you don't even need to specify the repository, you only need to specify the dependency.
