### ISSUE TITLE
"NoSuchElementException: Param earlyStoppingRound does not exist“ in mmlspark==0.12 & spark==2.2.1 when lightGBMClassifier().fit()  

### ISSUE THREAD

**Issue by yunnern** [Azure/mmlspark#851]
*Environment: mmlspark==0.12, spark==2.2.1
*Problem:
New to spark and apologize for any stupid question. When initializing a lightGBMClaasifier(),it's OK. While fitting train dataframe in spark, is showed error like this:' NoSuchElementException: Param earlyStoppingRound does not exist'. The error happened when pyspark.ml.Pipeline tried to run Params.getParam. I'm not sure what happened here.

**Comment by candalfigomoro** [comment]
mmlspark 0.12 is a very old version, there's not early stopping

**Comment by yunnern** [comment]
> mmlspark 0.12 is a very old version, there's not early stopping

Yes, it's quite old. While our spark is 2.2.1 and hardly to change in a short time, also our project is asked to use lightGBM model, mmlspark-0.12 seems to be the last resort. Let me dig deeper into the problems.

I downloaded the jar in maven and added to dependence in zepplin. When I run
 """from mmlspark import LightGBMClassifier
lgb = LightGBMClassifier()
lgb.getParam('earlyStoppingRound')
""", It' OK. And it showed:
![image](https://user-images.githubusercontent.com/44688824/79406304-4de18200-7fc9-11ea-9493-37f27c8e3324.png)
So I think this version may already have parameter 'earlyStopppingRound'. 

When I loaded some data, can try to fit the model like""" lgb.fit(train)""", It failed, and showed the info as below:
![image](https://user-images.githubusercontent.com/44688824/79407217-87b38800-7fcb-11ea-9b7f-d608a751dbd7.png)

So Is there any possible to run the code smoothly with mmlspark-0.12 and Spark-2.2.1, anything mismatched between spark.ml.Param & mmlspark.LightGBMClassifier()?

**Comment by candalfigomoro** [comment]
Early stopping and the support to provide an eval set for the early stopping are just not implemented in mmlspark 0.12, so also if you pass that parameter, you can't pass the eval set.

Just use LightGBM without Spark. If data is too big, perform an undersampling.

**Comment by yunnern** [comment]
> Early stopping and the support to provide an eval set for the early stopping are just not implemented in mmlspark 0.12, so also if you pass that parameter, you can't pass the eval set.
> 
> Just use LightGBM without Spark. If data is too big, perform an undersampling.

Ok, Thank you for your suggestion.

**Comment by imatiach-msft** [comment]
Closing as this is for a very old version of mmlspark and spark and earlyStoppingRound is now supported in the lightgbm learners.  Please reopen if there are still issues.
