### ISSUE TITLE
How do I create a pipeline for million individual timeseries ?

### ISSUE THREAD

**Issue by eromoe** [Azure/mmlspark#860]
Hello, 

I want to use quantile regression to generate upper_bound/lower_bound for million timeserires .

My current steps is below: 
```
prepare features
features groupby [product_id, store_id] ,  transform
transformed_features groupby [product_id, store_id] , train model
transformed_features groupby [product_id, store_id] , make prediction
```

Mainly using pyspark  `groupby().apply(pandas_udf)`  .  I didn't found a good way in sparkml to cope `groupby pipeline` .
I wonder if there is a better way by using mmlspark ?

**Comment by mhamilton723** [comment]
Sorry im not quite sure what you mean. Are you asking about the ability to perform a groupby as a SparkML Pipeline Stage?

**Comment by eromoe** [comment]
Yes, because I didn't see similar approach .

**Comment by mhamilton723** [comment]
You can do SQL operations using the `SQLTransformer` in regular Spark, we also provide a `Lambda` Transformer for more complex scala operations. Finally you can build one and make a PR to add it!
