### ISSUE TITLE
Can spark LightGBM support customized objective ? 

### ISSUE THREAD

**Issue by huaxz1986** [Azure/mmlspark#873]
When there is customized objective for python , is it avaliable for scala spark?

**Comment by imatiach-msft** [comment]
@huaxz1986 , sorry, it is not supported yet, will look into this as it seems to be a frequent ask.  Any ideas on how this might be technically achieved?

**Comment by robert-howley-zocdoc** [comment]
+1 on this idea. would be a very helpful feature

**Comment by imatiach-msft** [comment]
closing issue as this has been implemented in PR:
https://github.com/Azure/mmlspark/pull/1054
relevant issues:
https://github.com/Azure/mmlspark/issues/873, https://github.com/Azure/mmlspark/issues/871, https://github.com/Azure/mmlspark/issues/433
