### ISSUE TITLE
Provide sample on how to deploy a model in Spark 

### ISSUE THREAD

**Issue by gopitk** [Azure/mmlspark#88]
MMLSpark provides a way to save the model. It would be nice to take this to the next step to show how to  deploy the model to Spark using one of the methods - Spark UDF and/or Livy endpoint. It woudl be great to update one of the notebook to demostrate this.

**Comment by drdarshan** [comment]
Resolved as of PR #134 

There is now an example in the notebook showing structured streaming. Please reopen if you'd like something more.
