### ISSUE TITLE
AttributeError: 'DataStreamReader' object has no attribute 'server'

### ISSUE THREAD

**Issue by marekmoscichowski** [Azure/mmlspark#886]
Hi!

I'm trying to serve hello world example. Unfortunately, I'm getting
`AttributeError: 'DataStreamReader' object has no attribute 'server'` 

I tried running pyspark 
`pyspark --packages com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1`
also tried creating spark context with
`spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()`
I tried different versions of pyspark, different versions of mmlspark.
Trying different examples:
`mmlspark.cntk.CNTKModel()`
I was also missing dependency
`AttributeError: module 'mmlspark' has no attribute 'cntk'`

In the docs everything seems to work with no additional config, but it seems that I'm missing something.

Thank you in advance!
Marek

**Comment by mhamilton723** [comment]
hey @marekmoscichowski try our demo here
https://github.com/Azure/mmlspark/blob/master/notebooks/samples/SparkServing%20-%20Deploying%20a%20Classifier.ipynb

**Comment by mhamilton723** [comment]
Please feel free to reopen if the demo gives you issues, we test that on each check-in on azure databricks so it should work

**Comment by yashdiscite** [comment]
> hey @marekmoscichowski try our demo here https://github.com/Azure/mmlspark/blob/master/notebooks/samples/SparkServing%20-%20Deploying%20a%20Classifier.ipynb

Link is not active any more
