### ISSUE TITLE
Issues Fitting "Same" Data into Light GBM Classifier 

### ISSUE THREAD

**Issue by dantetrick** [Azure/mmlspark#887]
I have an issue fitting my data to a LightGBM Classifier that hopefully I can get some help with.

1. I have 1 notebook that works fine so I cloned it in order to try to optimize the flow.
2. The cloned notebook fails using nearly the same code on the same data. The difference between the codes is found in how I 'filter' out test and training data.
3. The row count is exactly the same when I try to fit() the model.
4. The notebook fails after I place a filter prior to the StringVectorization and OneHotEncoding steps instead of filtering out the data post steps. The actual data that is Vectorized and Encoded is the same columns between notebooks.
5. Below is a 1 row data sample of the data that goes into the 'working' classifier.
image
![image](https://user-images.githubusercontent.com/11829494/86834415-aae05780-c04f-11ea-9a14-7b46d089af3d.png)

![image](https://user-images.githubusercontent.com/11829494/86834367-9dc36880-c04f-11ea-9f60-75505810319e.png)

Below is a data sample of the same row of data that goes into the 'non-working' classifier as an example.
![image](https://user-images.githubusercontent.com/11829494/86836960-1c6dd500-c053-11ea-95ca-a103614c165e.png)

![image](https://user-images.githubusercontent.com/11829494/86836982-22fc4c80-c053-11ea-9e08-af22e942f459.png)

![image](https://user-images.githubusercontent.com/11829494/86837031-30b1d200-c053-11ea-96a3-df2cb4e776d4.png)

![image](https://user-images.githubusercontent.com/11829494/86837057-37d8e000-c053-11ea-8ad3-877dab0cf016.png)

NOTES:
A. The noticeable difference in the data is the numbers assigned to the column values from the indexer. I don't know why that would affect the fit() function but it may.
B. I updated to the newest snapshot of mmlspark and the error maintains

**Comment by imatiach-msft** [comment]
Discussed via Teams chat, we discovered there was an issue with the column names that caused LightGBM to fail.  Will be putting in a fix to improve the error message to detect the bad column names and fail early in the future as a follow-up.

**Comment by imatiach-msft** [comment]
closing issue as fix has been merged to master https://github.com/Azure/mmlspark/pull/897
