### ISSUE TITLE
"NoSuchElementException: Param lambdaL1 does not exist“ in mmlspark==0.17, spark==2.4.5, Databricks community edition when LightGBMRegressor().fit()

### ISSUE THREAD

**Issue by KeerthiNallagatla** [Azure/mmlspark#892]
*Environment: mmlspark==0.17, spark==2.4.5, Databricks community edition

*Problem:
New to spark and apologize for any stupid question. Trying to run 'LightGBM - Quantile Regression for Drug Discovery.ipynb'.  It fails while fitting the train data frame, throwing this error: ' java.util.NoSuchElementException: Param lambdaL1 does not exist'. I'm not sure what happened here.

**Comment by imatiach-msft** [comment]
@KeerthiNallagatla this parameter should exist in the latest version of mmlspark, I am guessing this is due to version 0.17 which is quite old.

**Comment by KeerthiNallagatla** [comment]
@imatiach-msft Thank you for replying. I am trying to install the latest version of mmlspark mentioned in this [link](https://github.com/Azure/mmlspark) using maven coordinates 'com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1' somehow it fails. Is there any other way how I can install the latest version?

**Comment by KeerthiNallagatla** [comment]
@imatiach-msft yes it was version issue. Thank you for the help
