### ISSUE TITLE
[Lightgbm] lightgbm ranker  categorical feature not work

### ISSUE THREAD

**Issue by ce39906** [Azure/mmlspark#900]
**Describe the bug**
Hi, @imatiach-msft , I'm using the latest version mmlspark to train a lightgbm ranker with categorical features, but it seems the function  “setCategoricalSlotIndexes” not work. I search "num_cat" in the model file and only found "num_cat = 0". 
When I use the local version lightgbm to train the same data,  I can find the "num_cat > 0" in the model file.
**To Reproduce**
Here is the train data.
https://github.com/ce39906/self-practices/tree/master/scratch
Here is my mmlspark training scala code
```
object TestCategoryFeature {

  def main(args: Array[String]) {
    val conf = new SparkConf()
    val sc = new SparkContext()
    val sqlContext = new HiveContext(sc)

    def loadTrainData() : DataFrame = {

      var df = sqlContext.read.format("csv").option("header", "true").option("sep","\t").load("viewfs://hadoop/features")
      df = df.selectExpr("cast(qid as bigint) qid", "feature", "cast(label as int) label")

      val toDenseFeatureUDF = udf((featuresStr : String) => {
        val features = new ListBuffer[Double]
        val featuresList = featuresStr.split(",")
        for (feature <- featuresList) {
          features.append(feature.toDouble)
        }

        Vectors.dense(features.toArray)
      })

      val df1 = df.withColumn("features", toDenseFeatureUDF(col("feature")))
        .select(
          col("qid"),
          col("features"),
          col("label"))
      df1
    }

    def train(df : DataFrame) : Unit = {
      val ranker = new LightGBMRanker()
      ranker.setParallelism("data_parallel")
        .setObjective("lambdarank")
        .setBoostingType("gbdt")
        .setNumIterations(500)
        .setLearningRate(0.1)
        .setNumLeaves(1023)
        .setMaxDepth(10)
        .setEarlyStoppingRound(0)
        .setMaxPosition(20)
        .setMinSumHessianInLeaf(0.001)
        .setLambdaL1(0.01)
        .setLambdaL2(0.01)
        .setIsProvideTrainingMetric(true)
        .setDefaultListenPort(49650)
        .setFeaturesCol("features")
        .setGroupCol("qid")
        .setLabelCol("label")
        .setNumBatches(0)
        .setTimeout(600000.0)
        .setVerbosity(1)
        .setCategoricalSlotIndexes(Array(0,1,2,3,4,5))

      val model = ranker.fit(df)
      val model_dir = "/user/hadoop/test_category"
      model.saveNativeModel(model_dir, true)
    }

    val df = loadTrainData()
    train(df)

    sc.stop()
  }
```
Here is a part of screenshot of mmlspark model file.
![image](https://user-images.githubusercontent.com/10767336/89143142-1f89b180-d57c-11ea-9bb1-97146809f443.png)

Here is my local train version python code
```
import sys, os
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.datasets import load_svmlight_file

def load_training_data(train_data, train_query):
    x_train, y_train = load_svmlight_file(os.path.join(os.path.dirname(os.path.realpath(__file__)), train_data))

    q_train = np.loadtxt(fname=train_query, dtype='int')
    return x_train, y_train.astype(int),  q_train

def lgb_train(x_train, y_train, q_train):
    params = {'boosting_type':'gbdt',
	      'num_leaves':15,
	      'max_depth':4,
	      'learning_rate':0.11,
	      'n_estimators':10,
	      'objective':'lambdarank'}

    data = lgb.Dataset(x_train, y_train , group=q_train, categorical_feature=[0,1,2,3,4,5])
    model = lgb.train(params, data)
    return model

def main():
    x_train, y_train, q_train = load_training_data('train.data', 'train.query')
    model = lgb_train(x_train, y_train, q_train)
    model.save_model('local_train.txt')

if __name__ == '__main__':
    main()
```
Here is a part of screenshot of the local model file
![image](https://user-images.githubusercontent.com/10767336/89143072-e2252400-d57b-11ea-9117-5832df04265b.png)

**Expected behavior**

**Info (please complete the following information):**
 - MMLSpark Version: v1.0.0-rc1
 - Spark Version: 2.2
 - Spark Platform: yarn

** Stacktrace**
```
Please post the stacktrace here if applicable
```
Here is the
If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by meowcakes** [comment]
This may be related to an issue I observed when trying to use the latest master build. In the executor logs I see
`[LightGBM] [Warning] Unknown parameter bin_construct_sample_cnt=200000categorical_feature=0,1,2,3,4,5,6,7,8,9,10`
It seems like the parameters aren't being correctly separated before being passed to LightGBM

**Comment by ce39906** [comment]
> This may be related to an issue I observed when trying to use the latest master build. In the executor logs I see
> `[LightGBM] [Warning] Unknown parameter bin_construct_sample_cnt=200000categorical_feature=0,1,2,3,4,5,6,7,8,9,10`
> It seems like the parameters aren't being correctly separated before being passed to LightGBM

Yes, I saw the similar log before.

**Comment by imatiach-msft** [comment]
great find, it looks like this PR caused the regression which is printing that warning:
https://github.com/Azure/mmlspark/pull/780
a space just needs to be added after bin_construct_sample_cnt=<number>
I wonder how this wasn't caught in the tests...

**Comment by ce39906** [comment]
![image](https://user-images.githubusercontent.com/10767336/89291575-5dc2c600-d68d-11ea-8dd0-863751563369.png)
hi, @imatiach-msft , I add a space in front of "categorical_feature=${trainParams.categoricalFeatures.mkString(",")}", and the categorical feature worked!
