### ISSUE TITLE
Make ImageReader fail fast if file path is invalid

### ISSUE THREAD

**Issue by rastala** [Azure/mmlspark#93]
Currently, if the path to images is incorrect, the ImageReader fails lazily when it tries to read images. This makes debugging hard because the failure might happen much later in the pipeline during some different operation.

Add check to ImageReader to validate the correctness and existence of the file path upon instantiation, for better debugging experience.

**Comment by mhamilton723** [comment]
Closing this issue as this issue is no longer applicable
