### ISSUE TITLE
Is there a list of LightGBMClassifier parameters somehwere?

### ISSUE THREAD

**Issue by amine000** [Azure/mmlspark#944]
Since it seems like the parameters supported by mmlspark.lightgbm.LightGBMClassifier are not the same as the ones supported by the standard LightGBM, and I cannot seem to find a reference of the supported parameters, can someone please point me to the parameters supported by  mmlspark.lightgbm.LightGBMClassifier?

**Comment by brunocous** [comment]
Most parameters of version 0.18.1 are still being used in the latest version: [](https://mmlspark.blob.core.windows.net/docs/0.18.1/pyspark/mmlspark.lightgbm.html).

**Comment by amine000** [comment]
@brunocous thank you!
