### ISSUE TITLE
Docker image with Python 2.7

### ISSUE THREAD

**Issue by usuyama** [Azure/mmlspark#95]
It'd be handy if we can use Python 2.7 out of the box. Currently, the image on Docker Hub (https://hub.docker.com/r/microsoft/mmlspark/) has only Python 3.5.

**Comment by mhamilton723** [comment]
@elibarzilay has this been adressed?

**Comment by mhamilton723** [comment]
Closing this issue as we are only supporting python 3.5 to minimize complexity
