### ISSUE TITLE
[LightGBM] Expose best iteration number when training with early stopping

### ISSUE THREAD

**Issue by stephane-leonard** [Azure/mmlspark#961]
**Is your feature request related to a problem? Please describe.**
When training a model with a number (x) for `earlyStoppingRound`, the training process ends once the validation error hasn't improved for x rounds. It's very useful to be able to identify the number of the best iteration to have an estimate of when (after how many rounds) the model starts overfitting.

**Describe the solution you'd like**
An accessible attribute of a trained model object.

**Additional context**
See [implementation](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html?highlight=best%20iteration#lightgbm.LGBMModel.best_iteration_) in LightGBM

**Comment by imatiach-msft** [comment]
fixed with PR #1024
